import type { NativeStackScreenProps } from "@react-navigation/native-stack";
import { useEffect, useState } from "react";
import { StyleSheet, Text, View } from "react-native";
import { loadTrainingAttempts } from "../../application/learningReadModels";
import { Button, Card, EmptyState, Screen } from "../../components";
import { ROUTES } from "../../constants";
import type { RootStackParamList } from "../../navigation";
import { useAppPreferences, useThemedStyles } from "../../preferences";
import { getCertificationContentCatalog } from "../../content/catalogRepository";
import { spacing, typography, type AppColors } from "../../theme";
type Props = NativeStackScreenProps<RootStackParamList, typeof ROUTES.EXAM_REVIEW>;
export function ExamReviewScreen({ navigation, route }: Props) { const styles = useThemedStyles(createStyles); const { t } = useAppPreferences(); const [rows, setRows] = useState<readonly { id: string; question: string; correct: boolean; explanation: string }[] | null>(null); useEffect(() => { void loadTrainingAttempts().then(({ value }) => setRows(value.filter((attempt) => attempt.sessionId === route.params.sessionId).map((attempt) => { const question = getCertificationContentCatalog().getItemById(attempt.item.itemId); return { id: attempt.id, question: question.question, correct: attempt.result.kind === "correct", explanation: question.explanation }; }))); }, [route.params.sessionId]); if (!rows) return <Screen><Text style={styles.loading}>{t("Loading review…")}</Text></Screen>; if (!rows.length) return <Screen><EmptyState title={t("No submitted answers")} description={t("This exam was finalized without answered questions.")} actionLabel={t("Back to practice")} onActionPress={() => navigation.navigate(ROUTES.PRACTICE_HUB)} /></Screen>; return <Screen style={styles.screen}>{rows.map((row) => <Card key={row.id} style={styles.card}><Text style={row.correct ? styles.correct : styles.incorrect}>{t(row.correct ? "Correct" : "Review")}</Text><Text style={styles.question}>{row.question}</Text><Text style={styles.explanation}>{row.explanation}</Text></Card>)}<Button onPress={() => navigation.navigate(ROUTES.PRACTICE_HUB)}>{t("Back to practice")}</Button></Screen>; }
const createStyles = (palette: AppColors) => StyleSheet.create({ screen: { gap: spacing.md }, loading: { ...typography.body, color: palette.textSecondary }, card: { gap: spacing.sm }, correct: { ...typography.small, color: palette.success }, incorrect: { ...typography.small, color: palette.danger }, question: { ...typography.bodyStrong, color: palette.textPrimary }, explanation: { ...typography.body, color: palette.textSecondary } });
