import assert from "node:assert/strict";
import test from "node:test";
import { recoverPendingMutation } from "../src/application/learningMutations/recoverPendingMutation";
import { JournalMaterializationError, JournalVerificationError, StorageReadError } from "../src/storage/errors";
import { STORAGE_KEYS } from "../src/storage/keys";
import { getActiveMutationJournal, persistMutationJournal } from "../src/storage/repositories/mutationJournalRepository";
import { getReviewQueueItems, getTrainingAttempts, getTrainingSessions } from "../src/storage/repositories";
import { materializeMutation } from "../src/application/learningMutations/mutationMaterializer";
import { installMemoryStorage, attempt, journal, review, session } from "./journalTestSupport";

function outcome() { return journal([{ kind: "put_attempt", record: attempt() }, { kind: "put_review_entry", record: review() }, { kind: "put_session", record: session("completed") }]); }
test("does nothing when no journal exists", async () => { installMemoryStorage(); await recoverPendingMutation(); assert.equal(await getActiveMutationJournal(), null); });
test("recovers a journal before any writes", async () => { installMemoryStorage(); await persistMutationJournal(outcome()); await recoverPendingMutation(); assert.equal((await getTrainingAttempts()).value.length, 1); assert.equal(await getActiveMutationJournal(), null); });
test("recovers partially materialized", async () => { installMemoryStorage(); const record = outcome(); await persistMutationJournal(record); await materializeMutation(journal([{ kind: "put_attempt", record: attempt() }])); await recoverPendingMutation(); assert.equal((await getReviewQueueItems()).value.length, 1); assert.equal(await getActiveMutationJournal(), null); });
test("fully materialized unverified", async () => { installMemoryStorage(); const record = outcome(); await persistMutationJournal(record); await materializeMutation(record); await recoverPendingMutation(); assert.equal(await getActiveMutationJournal(), null); });
test("verified journal whose clear failed", async () => { const storage = installMemoryStorage(); const record = outcome(); await persistMutationJournal(record); await materializeMutation(record); storage.setFailurePlan({ kind: "fail_on_key_remove", key: STORAGE_KEYS.ACTIVE_JOURNAL }); await assert.rejects(() => recoverPendingMutation()); storage.setFailurePlan(null); await recoverPendingMutation(); assert.equal(await getActiveMutationJournal(), null); });
test("accepts ident immutable attempt", async () => { installMemoryStorage(); const record = journal([{ kind: "put_attempt", record: attempt() }]); await persistMutationJournal(record); await materializeMutation(record); await recoverPendingMutation(); assert.equal((await getTrainingAttempts()).value.length, 1); });
test("rejects conflicting immutable attempt", async () => { installMemoryStorage(); await materializeMutation(journal([{ kind: "put_attempt", record: { ...attempt(), response: { choice: "b" } } }])); await persistMutationJournal(journal([{ kind: "put_attempt", record: attempt() }])); await assert.rejects(() => recoverPendingMutation(), JournalMaterializationError); });
test("rejects conflicting active journal", async () => { installMemoryStorage(); await persistMutationJournal(outcome()); await assert.rejects(() => persistMutationJournal({ ...journal([{ kind: "put_attempt", record: attempt("other") }]), journalId: "journal-other", inputFingerprint: "fingerprint-other" })) });
test("blocks corrupt journal", async () => { const storage = installMemoryStorage(); storage.setString(STORAGE_KEYS.ACTIVE_JOURNAL, "not-json"); await assert.rejects(() => recoverPendingMutation()); });
test("blocks journal read failure", async () => { const storage = installMemoryStorage(); storage.setFailurePlan({ kind: "fail_on_key_read", key: STORAGE_KEYS.ACTIVE_JOURNAL }); await assert.rejects(() => recoverPendingMutation(), StorageReadError); });
test("preserves journal after materialization failure", async () => { const storage = installMemoryStorage(); const record = outcome(); await persistMutationJournal(record); storage.setFailurePlan({ kind: "fail_on_key_write", key: STORAGE_KEYS.trainingAttempt("attempt-1") }); await assert.rejects(() => recoverPendingMutation(), JournalMaterializationError); assert.notEqual(await getActiveMutationJournal(), null); });
test("preserves journal after verification failure", async () => { const storage = installMemoryStorage(); const record = outcome(); await persistMutationJournal(record); await materializeMutation(record); storage.resetCounters(); storage.setFailurePlan({ kind: "fail_on_key_read", key: STORAGE_KEYS.TRAINING_ATTEMPT_INDEX }); await assert.rejects(() => recoverPendingMutation(), StorageReadError); storage.setFailurePlan(null); assert.notEqual(await getActiveMutationJournal(), null); });
test("preserves journal after journal clear failure", async () => { const storage = installMemoryStorage(); const record = outcome(); await persistMutationJournal(record); storage.setFailurePlan({ kind: "fail_on_key_remove", key: STORAGE_KEYS.ACTIVE_JOURNAL }); await assert.rejects(() => recoverPendingMutation()); assert.notEqual(await getActiveMutationJournal(), null); });
test("idempotent repeated recovery", async () => { installMemoryStorage(); await persistMutationJournal(outcome()); await recoverPendingMutation(); await recoverPendingMutation(); assert.equal((await getTrainingAttempts()).value.length, 1); assert.equal((await getTrainingSessions()).value.length, 1); });
test("does not require remote content", async () => { installMemoryStorage(); await persistMutationJournal(outcome()); await recoverPendingMutation(); assert.equal((await getTrainingAttempts()).value[0]?.item.itemId, "item-1"); });
test("does not recalc scoring", async () => { installMemoryStorage(); const record = outcome(); await persistMutationJournal(record); await recoverPendingMutation(); assert.deepEqual((await getTrainingAttempts()).value[0]?.result, attempt().result); });
test("does not generate IDs", async () => { installMemoryStorage(); await persistMutationJournal(outcome()); await recoverPendingMutation(); assert.equal((await getTrainingAttempts()).value[0]?.id, "attempt-1"); });
