import assert from "node:assert/strict";
import test, { beforeEach } from "node:test";
import { MemoryKeyValueStorage, installKeyValueStorageForTests } from "../src/infrastructure/storage/mmkvClient";
import { clearMutationJournal, getActiveMutationJournal, getTrainingAttempts, getTrainingSessions, persistMutationJournal } from "../src/storage";
import { buildMutationJournal, commitTrainingOutcome, recoverPendingMutation } from "../src/application/learningMutations";
beforeEach(() => installKeyValueStorageForTests(new MemoryKeyValueStorage()));
const session = { id: "s", trackId: "algorithms", modeId: "m", configurationSnapshot: { kind: "practice" }, requestedLength: 1, actualLength: 1, currentItemIndex: 0, itemOrder: [{ occurrenceId: "occurrence-1", item: { trackId: "algorithms", itemId: "i", contentVersion: "v" } }], optionOrderByOccurrence: {}, flaggedOccurrenceIds: [], activeForegroundMs: 0, contentVersion: "v", status: "active" as const, startedAt: "2026-01-01T00:00:00.000Z" };
const attempt = { id: "a", sessionId: "s", trackId: "algorithms", modeId: "m", occurrenceId: "occurrence-1", item: session.itemOrder[0]!.item, response: { ids: ["x"] }, result: { kind: "correct" as const, earnedPoints: 1, maxPoints: 1 }, reviewEvidence: { sourceItem: session.itemOrder[0]!.item, taxonomyOrSkillRefs: [] }, answeredAt: session.startedAt, committedAt: session.startedAt };
test("journal durability precedes idempotent materialization and recovery", async () => { const record = await buildMutationJournal({ operation: "submit_training_outcome", sessionId: "s", trackId: "algorithms", identity: attempt.response, writes: [{ kind: "put_attempt", record: attempt }, { kind: "put_session", record: session }], createdAt: session.startedAt }); await persistMutationJournal(record); assert.equal((await getTrainingAttempts()).value.length, 0); await recoverPendingMutation(); assert.equal((await getActiveMutationJournal()), null); assert.equal((await getTrainingAttempts()).value.length, 1); assert.equal((await getTrainingSessions()).value.length, 1); await recoverPendingMutation(); assert.equal((await getTrainingAttempts()).value.length, 1); });
test("journaled command rejects a conflicting pending command", async () => { const record = await buildMutationJournal({ operation: "submit_training_outcome", sessionId: "s", trackId: "algorithms", identity: "other", writes: [{ kind: "put_attempt", record: attempt }, { kind: "put_session", record: session }], createdAt: session.startedAt }); await persistMutationJournal(record); await assert.rejects(commitTrainingOutcome({ attempt, session, reviews: [], createdAt: session.startedAt })); });
test("concurrent conflicting journal persists use one CAS winner and ownership-checked clear", async () => {
  const make = (identity: string) => buildMutationJournal({ operation: "submit_training_outcome" as const, sessionId: "s", trackId: "algorithms", identity, writes: [{ kind: "put_attempt" as const, record: attempt }, { kind: "put_session" as const, record: session }], createdAt: session.startedAt });
  const [left, right] = await Promise.all([make("left"), make("right")]);
  const outcomes = await Promise.allSettled([persistMutationJournal(left), persistMutationJournal(right)]);
  assert.equal(outcomes.filter((outcome) => outcome.status === "fulfilled").length, 1);
  assert.equal(outcomes.filter((outcome) => outcome.status === "rejected").length, 1);
  const durable = await getActiveMutationJournal();
  assert.ok(durable);
  const loser = durable.commandFingerprint === left.commandFingerprint ? right : left;
  await assert.rejects(clearMutationJournal(loser.commandFingerprint), /ownership/);
  assert.equal((await getActiveMutationJournal())?.commandFingerprint, durable.commandFingerprint);
  await clearMutationJournal(durable.commandFingerprint);
  assert.equal(await getActiveMutationJournal(), null);
});
