import type { ReviewReason, TrainingAttempt } from "../../domain";
import { isAlgorithmChoiceQuestion, isAlgorithmComplexityQuestion, isAlgorithmOrderingQuestion, type AlgorithmQuestion } from "./algorithmQuestionTypes";
import { scoreAlgorithmQuestion, type AlgorithmQuestionScore } from "./algorithmScoring";
import type { AlgorithmResponse } from "./domain";

export type AlgorithmInteractionKind = "choice" | "ordering" | "complexity";
export type AlgorithmInteractionCompleteness = Readonly<{ complete: boolean; missing: readonly string[] }>;
export type AlgorithmAuthoredFeedback = Readonly<{ details: string; omittedCorrectOptionExplanations: readonly Readonly<{ optionId: string; text: string }>[]; reason: string; wrongOptionExplanations: readonly Readonly<{ optionId: string; text: string }>[] }>;
export type AlgorithmRendererState = Readonly<{ kind: "choice"; options: readonly Readonly<{ id: string; selected: boolean; text: string }>[] }> | Readonly<{ kind: "ordering"; elements: readonly Readonly<{ id: string; text: string }>[] }> | Readonly<{ dimensions: readonly Readonly<{ id: string; selectedValue?: string; values: readonly string[] }>[]; kind: "complexity" }>;
export type AlgorithmAccessibilityViewModel = Readonly<{ controls: readonly Readonly<{ checked?: boolean; id: string; label: string; role: "checkbox" | "radio" | "option" | "select" }>[]; interactionKind: AlgorithmInteractionKind; label: string }>;
export class AlgorithmInteractionContentError extends Error { constructor(readonly itemId: string, readonly defect: string) { super(`Algorithms content defect in ${itemId}: ${defect}`); this.name = "AlgorithmInteractionContentError"; } }

export function validateAlgorithmInteractionItem(item: AlgorithmQuestion): void {
  requireText(item, item.feedback.reason, "missing authored Reason"); requireText(item, item.feedback.details, "missing authored Details");
  if (isAlgorithmChoiceQuestion(item)) return validateChoice(item);
  if (isAlgorithmOrderingQuestion(item)) { const { elements, canonicalOrder, scoringMethod } = item.interaction; if (scoringMethod !== "adjacent_relations" || elements.length < 2 || canonicalOrder.length !== elements.length || new Set(elements.map((entry) => entry.id)).size !== elements.length || new Set(canonicalOrder).size !== elements.length || canonicalOrder.some((id) => !elements.some((entry) => entry.id === id)) || item.scoringContract.maxPoints !== elements.length - 1) fail(item, "ordering contract is invalid"); return; }
  if (isAlgorithmComplexityQuestion(item)) { const interaction = item.interaction; if (interaction.checkedDimensions.length === 0 || new Set(interaction.checkedDimensions).size !== interaction.checkedDimensions.length || interaction.maxPoints !== interaction.checkedDimensions.length || item.scoringContract.maxPoints !== interaction.maxPoints) fail(item, "complexity contract is invalid"); for (const dimension of interaction.checkedDimensions) { const available = interaction.availableValuesByDimension[dimension]; const accepted = interaction.acceptedValuesByDimension[dimension]; if (!available?.length || !accepted?.length || accepted.some((value) => !available.includes(value))) fail(item, `complexity dimension ${dimension} is incomplete`); for (const target of Object.values(interaction.normalizedAliasesByDimension[dimension] ?? {})) if (!available.includes(target)) fail(item, `complexity dimension ${dimension} has unknown alias target`); } return; }
  fail(item, "unsupported active interaction type");
}
export function getAlgorithmInteractionCompleteness(item: AlgorithmQuestion, response: AlgorithmResponse | null): AlgorithmInteractionCompleteness {
  if (!response) return Object.freeze({ complete: false, missing: Object.freeze(["response"]) });
  if (isAlgorithmChoiceQuestion(item)) return Object.freeze({ complete: response.kind === "choice" && response.selectedOptionIds.length > 0, missing: response.kind === "choice" && response.selectedOptionIds.length > 0 ? Object.freeze([]) : Object.freeze(["selection"]) });
  if (isAlgorithmOrderingQuestion(item)) return Object.freeze({ complete: response.kind === "ordering" && response.orderedSubgoalIds.length === item.interaction.canonicalOrder.length, missing: response.kind === "ordering" && response.orderedSubgoalIds.length === item.interaction.canonicalOrder.length ? Object.freeze([]) : Object.freeze(["ordered_elements"]) });
  if (isAlgorithmComplexityQuestion(item)) { const missing = item.interaction.checkedDimensions.filter((dimension) => response.kind !== "complexity" || !response.selectedValuesByDimension[dimension]); return Object.freeze({ complete: response.kind === "complexity" && missing.length === 0, missing: Object.freeze(missing) }); }
  return Object.freeze({ complete: false, missing: Object.freeze(["unsupported_interaction"]) });
}
export function submitAlgorithmInteraction(input: Readonly<{ question: AlgorithmQuestion; response: AlgorithmResponse }>): Readonly<{ feedback: AlgorithmAuthoredFeedback; score: AlgorithmQuestionScore }> { validateAlgorithmInteractionItem(input.question); const completeness = getAlgorithmInteractionCompleteness(input.question, input.response); if (!completeness.complete) throw new Error(`Algorithms response for ${input.question.id} is incomplete: ${completeness.missing.join(", ")}.`); const score = scoreAlgorithmQuestion(input.question, input.response); return Object.freeze({ feedback: composeAlgorithmAuthoredFeedback(input.question, score), score }); }
export function composeAlgorithmAuthoredFeedback(item: AlgorithmQuestion, score: AlgorithmQuestionScore): AlgorithmAuthoredFeedback { validateAlgorithmInteractionItem(item); const wrong = score.diagnostics.selectedWrongOptionIds.map((id) => requiredOptionExplanation(item, item.feedback.wrongOptionExplanationsByOptionId, id, "selected wrong option")); const omitted = score.diagnostics.omittedCorrectOptionIds.map((id) => omittedCorrectExplanation(item, id)); return Object.freeze({ details: item.feedback.details, reason: item.feedback.reason, wrongOptionExplanations: Object.freeze(wrong), omittedCorrectOptionExplanations: Object.freeze(omitted) }); }
/** Rehydrates display feedback inside Algorithms semantics and verifies its durable result. */
export function composeCommittedAlgorithmPracticeFeedback(input: Readonly<{ question: AlgorithmQuestion; attempt: TrainingAttempt<AlgorithmResponse> }>) {
  const score = scoreAlgorithmQuestion(input.question, input.attempt.response);
  if (score.result.kind !== input.attempt.result.kind || score.result.earnedPoints !== input.attempt.result.earnedPoints || score.result.maxPoints !== input.attempt.result.maxPoints) {
    throw new Error("Committed Algorithms attempt result does not match its immutable response.");
  }
  const controls = (() => {
    const { question } = input;
    const response = input.attempt.response;
    if (!isAlgorithmChoiceQuestion(question) || response.kind !== "choice") return Object.freeze([] as readonly Readonly<{ id: string; state: "selected" | "correct" | "incorrect" | "omitted_correct" | "neutral" }> []);
    return Object.freeze(question.interaction.options.map((option) => Object.freeze({
      id: option.id,
      state: response.selectedOptionIds.includes(option.id) && score.diagnostics.selectedWrongOptionIds.includes(option.id)
        ? "incorrect" as const
        : !response.selectedOptionIds.includes(option.id) && score.diagnostics.omittedCorrectOptionIds.includes(option.id)
          ? "omitted_correct" as const
          : response.selectedOptionIds.includes(option.id) && question.interaction.acceptedOptionIds.includes(option.id)
            ? "correct" as const
            : response.selectedOptionIds.includes(option.id) ? "selected" as const : "neutral" as const,
    })));
  })();
  return Object.freeze({ correctness: input.attempt.result.kind, ...composeAlgorithmAuthoredFeedback(input.question, score), controls });
}
export function buildAlgorithmInteractionViewModel(item: AlgorithmQuestion, response: AlgorithmResponse | null): Readonly<{ accessibility: AlgorithmAccessibilityViewModel; renderer: AlgorithmRendererState }> { validateAlgorithmInteractionItem(item); if (isAlgorithmChoiceQuestion(item)) { const selected = response?.kind === "choice" ? new Set(response.selectedOptionIds) : new Set<string>(); const options = Object.freeze(item.interaction.options.map((option) => Object.freeze({ id: option.id, selected: selected.has(option.id), text: option.text }))); const role = item.interaction.selectionMode === "multiple" ? "checkbox" as const : "radio" as const; return Object.freeze({ accessibility: Object.freeze({ controls: Object.freeze(options.map((option) => Object.freeze({ checked: option.selected, id: option.id, label: option.text, role }))), interactionKind: "choice", label: item.prompt }), renderer: Object.freeze({ kind: "choice", options }) }); } if (isAlgorithmOrderingQuestion(item)) { const ordered = response?.kind === "ordering" ? response.orderedSubgoalIds : item.interaction.elements.map((entry) => entry.id); const textById = new Map(item.interaction.elements.map((entry) => [entry.id, entry.text])); const elements = Object.freeze(ordered.map((id) => Object.freeze({ id, text: textById.get(id) ?? id }))); return Object.freeze({ accessibility: Object.freeze({ controls: Object.freeze(elements.map((entry) => Object.freeze({ id: entry.id, label: entry.text, role: "option" as const }))), interactionKind: "ordering", label: item.prompt }), renderer: Object.freeze({ kind: "ordering", elements }) }); } if (isAlgorithmComplexityQuestion(item)) { const selected = response?.kind === "complexity" ? response.selectedValuesByDimension : {}; const dimensions = Object.freeze(item.interaction.checkedDimensions.map((id) => Object.freeze({ id, ...(selected[id] ? { selectedValue: selected[id] } : {}), values: Object.freeze([...(item.interaction.availableValuesByDimension[id] ?? [])]) }))); return Object.freeze({ accessibility: Object.freeze({ controls: Object.freeze(dimensions.map((entry) => Object.freeze({ id: entry.id, label: entry.id, role: "select" as const }))), interactionKind: "complexity", label: item.prompt }), renderer: Object.freeze({ kind: "complexity", dimensions }) }); } return fail(item, "unsupported active interaction type"); }
export function deriveAlgorithmReviewReasons(input: Readonly<{ priorAttemptsForSameItem: readonly TrainingAttempt[]; score: AlgorithmQuestionScore }>): readonly ReviewReason[] { if (input.score.status === "correct") return Object.freeze([]); const reasons = new Set<ReviewReason>([input.score.status]); if (input.score.diagnostics.selectedWrongOptionIds.length) reasons.add("wrong_strategy"); if (input.score.diagnostics.incorrectComplexityDimensionIds.length) reasons.add("complexity_error"); if (input.score.diagnostics.brokenOrderingRelations.length) reasons.add("wrong_pattern"); if (input.priorAttemptsForSameItem.some((attempt) => attempt.result.kind !== "correct")) reasons.add("repeated_mistake"); return Object.freeze([...reasons]); }
function validateChoice(item: Extract<AlgorithmQuestion, { interaction: { type: "choice" } }>): void { const { acceptedOptionIds, options, selectionMode } = item.interaction; if (item.scoringContract.type !== "choice" || item.scoringContract.resultSemantics !== "exact_selected_set_with_partial_v1" || options.length < 2 || new Set(options.map((option) => option.id)).size !== options.length || options.some((option) => !option.id.trim() || !option.text.trim()) || !acceptedOptionIds.length || new Set(acceptedOptionIds).size !== acceptedOptionIds.length || acceptedOptionIds.some((id) => !options.some((option) => option.id === id)) || (selectionMode === "single" && acceptedOptionIds.length !== 1)) fail(item, "choice contract is invalid"); const wrong = options.filter((option) => !acceptedOptionIds.includes(option.id)); if (wrong.some((option) => !item.feedback.wrongOptionExplanationsByOptionId?.[option.id]?.trim())) fail(item, "every wrong choice option requires an authored stable-ID explanation"); if (selectionMode === "multiple" && acceptedOptionIds.some((id) => !item.feedback.omittedCorrectExplanationsByOptionId?.[id]?.trim())) fail(item, "multiple-choice requires authored omitted-correct explanations"); }
function requiredOptionExplanation(item: AlgorithmQuestion, values: Readonly<Record<string, string>> | undefined, optionId: string, label: string) { const text = values?.[optionId]; if (!text?.trim()) fail(item, `missing authored explanation for ${label}`); return Object.freeze({ optionId, text }); }
/** Omitted-correct explanations are optional in the published contract; mandatory Details is their canonical general explanation. */
function omittedCorrectExplanation(item: AlgorithmQuestion, optionId: string) { const text = item.feedback.omittedCorrectExplanationsByOptionId?.[optionId] ?? item.feedback.details; if (!text.trim()) fail(item, "missing authored explanation for omitted correct option"); return Object.freeze({ optionId, text }); }
function requireText(item: AlgorithmQuestion, value: string | undefined, defect: string): void { if (!value?.trim()) fail(item, defect); }
function fail(item: AlgorithmQuestion, defect: string): never { throw new AlgorithmInteractionContentError(item.id, defect); }
