import {
  ALGORITHM_CONTENT_VERSION,
  type AlgorithmPatternFamily,
  type AlgorithmPatternVariant,
  type AlgorithmProblemArchetype,
  type AlgorithmSkillAtom,
} from "./algorithmContentTypes";

export const ALGORITHM_PATTERN_FAMILIES = [
  {
    commonMistakeTypes: [
      "brute_force_when_optimized_required",
      "complexity_mismatch",
      "constraint_ignored",
      "cannot_explain_why",
    ],
    contentVersion: ALGORITHM_CONTENT_VERSION,
    coreDecisionSignals: [
      "Large input size makes nested enumeration too expensive.",
      "The prompt asks whether an approach will scale before asking for implementation details.",
    ],
    description: "Foundational reasoning about input limits, Big O cost, and when direct enumeration fails.",
    entryLearningStage: "foundations",
    id: "complexity_basics",
    label: "Complexity basics",
    prerequisitePatternFamilyIds: [],
  },
  {
    commonMistakeTypes: [
      "data_structure_mismatch",
      "duplicate_handling_error",
      "cannot_explain_why",
    ],
    contentVersion: ALGORITHM_CONTENT_VERSION,
    coreDecisionSignals: [
      "The solution needs quick membership, frequency, or complement lookup.",
      "The relevant relationship can be checked while scanning once.",
    ],
    description: "Use maps and sets to remember values, counts, or complements during a scan.",
    entryLearningStage: "pattern_mechanics",
    id: "hash_map_and_set",
    label: "Hash map and set",
    prerequisitePatternFamilyIds: ["complexity_basics"],
  },
  {
    commonMistakeTypes: [
      "wrong_approach",
      "constraint_ignored",
      "off_by_one",
      "duplicate_handling_error",
    ],
    contentVersion: ALGORITHM_CONTENT_VERSION,
    coreDecisionSignals: [
      "The input is sorted or can be ordered without losing the required relationship.",
      "A pair or boundary condition can be improved by moving one side inward.",
    ],
    description: "Coordinate two moving positions, usually on sorted data or bounded ranges.",
    entryLearningStage: "pattern_mechanics",
    id: "two_pointers",
    label: "Two pointers",
    prerequisitePatternFamilyIds: ["complexity_basics"],
  },
  {
    commonMistakeTypes: [
      "invariant_missing",
      "invariant_broken",
      "negative_numbers_assumption_error",
      "cannot_trace_algorithm",
    ],
    contentVersion: ALGORITHM_CONTENT_VERSION,
    coreDecisionSignals: [
      "The problem asks about a contiguous range.",
      "Extending or shrinking the range changes the state predictably enough to maintain an invariant.",
    ],
    description: "Maintain a moving contiguous range while updating the state needed to test a condition.",
    entryLearningStage: "pattern_mechanics",
    id: "sliding_window",
    label: "Sliding window",
    prerequisitePatternFamilyIds: ["complexity_basics", "two_pointers"],
  },
  {
    commonMistakeTypes: [
      "wrong_approach",
      "constraint_ignored",
      "negative_numbers_assumption_error",
      "edge_case_missed",
    ],
    contentVersion: ALGORITHM_CONTENT_VERSION,
    coreDecisionSignals: [
      "The problem asks about range totals, differences, or repeated subarray sums.",
      "Values may break the monotonic behavior needed by a simple window.",
    ],
    description: "Reuse accumulated values to answer range or subarray questions without recomputing each range.",
    entryLearningStage: "pattern_mechanics",
    id: "prefix_sums",
    label: "Prefix sums",
    prerequisitePatternFamilyIds: ["complexity_basics", "hash_map_and_set"],
  },
  {
    commonMistakeTypes: [
      "wrong_approach",
      "complexity_mismatch",
      "constraint_ignored",
      "duplicate_handling_error",
    ],
    contentVersion: ALGORITHM_CONTENT_VERSION,
    coreDecisionSignals: [
      "Ordering simplifies comparisons, grouping, or interval merging.",
      "The cost of sorting is acceptable for the input limits and preserves the needed answer.",
    ],
    description: "Sort input or derived records when ordering reveals a simpler scan or comparison.",
    entryLearningStage: "strategy_selection",
    id: "sorting_based",
    label: "Sorting based",
    prerequisitePatternFamilyIds: ["complexity_basics"],
  },
  {
    commonMistakeTypes: [
      "data_structure_mismatch",
      "cannot_trace_algorithm",
      "edge_case_missed",
      "invariant_broken",
    ],
    contentVersion: ALGORITHM_CONTENT_VERSION,
    coreDecisionSignals: [
      "The most recent unresolved element controls the next decision.",
      "Nested or next-greater structure requires last-in-first-out state.",
    ],
    description: "Use last-in-first-out state for nested structures, unresolved boundaries, or monotonic scans.",
    entryLearningStage: "pattern_mechanics",
    id: "stack",
    label: "Stack",
    prerequisitePatternFamilyIds: ["complexity_basics"],
  },
  {
    commonMistakeTypes: [
      "wrong_approach",
      "constraint_ignored",
      "off_by_one",
      "cannot_explain_why",
    ],
    contentVersion: ALGORITHM_CONTENT_VERSION,
    coreDecisionSignals: [
      "The input or answer space has an ordered yes/no boundary.",
      "Each check can discard a half or a large ordered region.",
    ],
    description: "Use ordered structure to shrink the search space through repeated comparisons.",
    entryLearningStage: "pattern_mechanics",
    id: "binary_search",
    label: "Binary search",
    prerequisitePatternFamilyIds: ["complexity_basics"],
  },
] as const satisfies readonly AlgorithmPatternFamily[];

export const ALGORITHM_PATTERN_VARIANTS = [
  {
    contentVersion: ALGORITHM_CONTENT_VERSION,
    decisionSignals: ["Membership or complement lookup is enough to avoid checking every pair."],
    description: "Store seen values, counts, or complements for average constant-time lookup.",
    id: "hash_map_average_lookup",
    label: "Average lookup",
    learningStage: "pattern_mechanics",
    patternFamilyId: "hash_map_and_set",
    prerequisitePatternFamilyIds: ["complexity_basics"],
  },
  {
    contentVersion: ALGORITHM_CONTENT_VERSION,
    decisionSignals: ["All values are positive, so expanding and shrinking the window changes the sum predictably."],
    description: "Move both window boundaries forward while preserving a sum or count invariant.",
    id: "variable_size_positive_window",
    label: "Variable size positive window",
    learningStage: "pattern_mechanics",
    patternFamilyId: "sliding_window",
    prerequisitePatternFamilyIds: ["complexity_basics", "two_pointers"],
  },
  {
    contentVersion: ALGORITHM_CONTENT_VERSION,
    decisionSignals: ["Subarray sums may include negative values, so a monotonic window is not reliable."],
    description: "Combine accumulated sums with lookup to reason about arbitrary subarray totals.",
    id: "prefix_sum_with_hash_map",
    label: "Prefix sum with hash map",
    learningStage: "contrast_practice",
    patternFamilyId: "prefix_sums",
    prerequisitePatternFamilyIds: ["complexity_basics", "hash_map_and_set"],
  },
  {
    contentVersion: ALGORITHM_CONTENT_VERSION,
    decisionSignals: ["A sorted input plus a pair condition lets one pointer move based on comparison to target."],
    description: "Scan inward over sorted input to find or rule out a pair condition.",
    id: "sorted_pair_two_pointers",
    label: "Sorted pair two pointers",
    learningStage: "pattern_mechanics",
    patternFamilyId: "two_pointers",
    prerequisitePatternFamilyIds: ["complexity_basics"],
  },
  {
    contentVersion: ALGORITHM_CONTENT_VERSION,
    decisionSignals: ["The target can be compared against a sorted sequence at a midpoint."],
    description: "Use midpoint comparisons to locate a value or insertion boundary.",
    id: "classic_index_binary_search",
    label: "Classic index search",
    learningStage: "pattern_mechanics",
    patternFamilyId: "binary_search",
    prerequisitePatternFamilyIds: ["complexity_basics"],
  },
  {
    contentVersion: ALGORITHM_CONTENT_VERSION,
    decisionSignals: ["The next valid action depends on the most recent unmatched opening structure."],
    description: "Push unresolved openings and pop them when a matching closing structure appears.",
    id: "nested_structure_stack",
    label: "Nested structure stack",
    learningStage: "pattern_mechanics",
    patternFamilyId: "stack",
    prerequisitePatternFamilyIds: ["complexity_basics"],
  },
] as const satisfies readonly AlgorithmPatternVariant[];

export const ALGORITHM_PROBLEM_ARCHETYPES = [
  {
    contentVersion: ALGORITHM_CONTENT_VERSION,
    decisionSignals: ["Find whether two elements satisfy a relationship under ordering or lookup constraints."],
    description: "Pair selection where the main decision is whether lookup, sorting, or inward scanning fits.",
    id: "find_pair_with_condition",
    label: "Find pair with condition",
    primaryPatternFamilyIds: ["hash_map_and_set", "two_pointers", "sorting_based"],
  },
  {
    contentVersion: ALGORITHM_CONTENT_VERSION,
    decisionSignals: ["The answer depends on a contiguous section and the state of that section."],
    description: "Contiguous range problems where the state can be updated as boundaries move.",
    id: "find_subarray_with_target",
    label: "Find subarray with target",
    primaryPatternFamilyIds: ["sliding_window", "prefix_sums"],
  },
  {
    contentVersion: ALGORITHM_CONTENT_VERSION,
    decisionSignals: ["Correctness depends on the most recent unresolved opening or boundary."],
    description: "Nested syntax or structure validation through last-in-first-out state.",
    id: "validate_nested_structure",
    label: "Validate nested structure",
    primaryPatternFamilyIds: ["stack"],
  },
  {
    contentVersion: ALGORITHM_CONTENT_VERSION,
    decisionSignals: ["A sorted sequence can be repeatedly split by comparison to a target or boundary."],
    description: "Locate a value, boundary, or insertion point in ordered input.",
    id: "find_index_in_sorted_input",
    label: "Find index in sorted input",
    primaryPatternFamilyIds: ["binary_search"],
  },
] as const satisfies readonly AlgorithmProblemArchetype[];

export const ALGORITHM_SKILL_ATOMS = [
  {
    contentVersion: ALGORITHM_CONTENT_VERSION,
    description: "Use input constraints to reject nested pair enumeration when the input can be very large.",
    evidenceRequiredForProgression: ["explained", "guided"],
    id: "recognize_n2_too_slow_for_large_n",
    label: "Reject quadratic work for large n",
    mistakeTypes: [
      "brute_force_when_optimized_required",
      "complexity_mismatch",
      "constraint_ignored",
    ],
    primaryPatternFamilyId: "complexity_basics",
    prerequisiteSkillAtomIds: [],
  },
  {
    contentVersion: ALGORITHM_CONTENT_VERSION,
    description: "Explain why a map or set can make membership, count, or complement checks efficient on average.",
    evidenceRequiredForProgression: ["explained", "guided"],
    id: "explain_hash_map_average_lookup",
    label: "Explain average lookup",
    mistakeTypes: ["data_structure_mismatch", "cannot_explain_why"],
    patternVariantIds: ["hash_map_average_lookup"],
    primaryPatternFamilyId: "hash_map_and_set",
    problemArchetypeIds: ["find_pair_with_condition"],
    prerequisiteSkillAtomIds: ["recognize_n2_too_slow_for_large_n"],
  },
  {
    contentVersion: ALGORITHM_CONTENT_VERSION,
    description: "Track what must remain true as a contiguous window expands and shrinks.",
    evidenceRequiredForProgression: ["traced", "guided"],
    id: "maintain_sliding_window_invariant",
    label: "Maintain window invariant",
    mistakeTypes: ["invariant_missing", "invariant_broken", "cannot_trace_algorithm"],
    patternVariantIds: ["variable_size_positive_window"],
    primaryPatternFamilyId: "sliding_window",
    problemArchetypeIds: ["find_subarray_with_target"],
    prerequisiteSkillAtomIds: ["recognize_n2_too_slow_for_large_n"],
  },
  {
    contentVersion: ALGORITHM_CONTENT_VERSION,
    description: "Recognize that positive values make simple sum-window movement predictable.",
    evidenceRequiredForProgression: ["explained", "guided"],
    id: "recognize_positive_numbers_sliding_window_signal",
    label: "Recognize positive-window signal",
    mistakeTypes: ["constraint_ignored", "cannot_explain_why"],
    patternVariantIds: ["variable_size_positive_window"],
    primaryPatternFamilyId: "sliding_window",
    problemArchetypeIds: ["find_subarray_with_target"],
    prerequisiteSkillAtomIds: ["maintain_sliding_window_invariant"],
  },
  {
    contentVersion: ALGORITHM_CONTENT_VERSION,
    description: "Detect when negative values break the simple sum-window assumption and point toward prefix sums.",
    evidenceRequiredForProgression: ["contrast_success", "needs_review"],
    id: "detect_negative_numbers_break_simple_window_sum",
    label: "Detect negative-number window break",
    mistakeTypes: [
      "negative_numbers_assumption_error",
      "invariant_broken",
      "wrong_approach",
    ],
    patternVariantIds: ["prefix_sum_with_hash_map"],
    primaryPatternFamilyId: "prefix_sums",
    problemArchetypeIds: ["find_subarray_with_target"],
    prerequisiteSkillAtomIds: ["recognize_positive_numbers_sliding_window_signal"],
  },
  {
    contentVersion: ALGORITHM_CONTENT_VERSION,
    description: "Choose inward scanning when sorted input and a pair condition make pointer movement decisive.",
    evidenceRequiredForProgression: ["explained", "guided"],
    id: "choose_two_pointers_for_sorted_pair_condition",
    label: "Choose two pointers for sorted pair",
    mistakeTypes: ["wrong_approach", "constraint_ignored", "off_by_one"],
    patternVariantIds: ["sorted_pair_two_pointers"],
    primaryPatternFamilyId: "two_pointers",
    problemArchetypeIds: ["find_pair_with_condition"],
    prerequisiteSkillAtomIds: ["recognize_n2_too_slow_for_large_n"],
  },
  {
    contentVersion: ALGORITHM_CONTENT_VERSION,
    description: "Identify sorted input or an ordered boundary as the key signal for binary search.",
    evidenceRequiredForProgression: ["explained", "guided"],
    id: "identify_binary_search_sorted_input_signal",
    label: "Identify sorted-input search signal",
    mistakeTypes: ["wrong_approach", "constraint_ignored", "off_by_one"],
    patternVariantIds: ["classic_index_binary_search"],
    primaryPatternFamilyId: "binary_search",
    problemArchetypeIds: ["find_index_in_sorted_input"],
    prerequisiteSkillAtomIds: ["recognize_n2_too_slow_for_large_n"],
  },
  {
    contentVersion: ALGORITHM_CONTENT_VERSION,
    description: "Explain why nested or most-recent-unresolved structures fit stack state.",
    evidenceRequiredForProgression: ["explained", "traced"],
    id: "explain_stack_for_nested_structure",
    label: "Explain stack for nested structure",
    mistakeTypes: ["data_structure_mismatch", "cannot_trace_algorithm", "edge_case_missed"],
    patternVariantIds: ["nested_structure_stack"],
    primaryPatternFamilyId: "stack",
    problemArchetypeIds: ["validate_nested_structure"],
    prerequisiteSkillAtomIds: ["recognize_n2_too_slow_for_large_n"],
  },
] as const satisfies readonly AlgorithmSkillAtom[];
