import type { AlgorithmQuestion } from "../../../algorithmQuestionTypes";

export const recognizeSlidingWindowVsPrefixSumsStrategySignalQuestions = [
  {
    "contentVersion": "algorithms-core",
    "difficulty": "intro",
    "id": "alg-contrast-sliding-window-prefix-recognize-001",
    "learningStage": "foundations",
    "primarySkillAtomId": "recognize_sliding_window_vs_prefix_sum_signal",
    "secondarySkillAtomIds": [
      "moving_contiguous_range",
      "static_range_query_preprocessing"
    ],
    "type": "single_choice",
    "prompt": "You must find the largest sum among all consecutive blocks of exactly k values in one left-to-right pass. Which strategy best matches the access pattern?",
    "feedbackModel": {
      "decisionSignal": "The task evaluates neighboring candidate ranges in one monotonic traversal.",
      "mentalModelCorrection": "A rolling window is indicated by reusable state between consecutive ranges, not merely by the presence of a sum.",
      "mistakeTypes": [
        "strategy_signal_mismatch"
      ],
      "nextAction": "Check whether each next range differs from the current range only at its boundaries.",
      "result": "diagnostic"
    },
    "options": [
      {
        "id": "rolling_window",
        "text": "Maintain one current length-k range and update its aggregate as the range moves.",
        "isCorrect": true
      },
      {
        "id": "prefix_queries",
        "text": "Treat every candidate range as an independently supplied static query.",
        "isCorrect": false
      },
      {
        "id": "global_total",
        "text": "Compute only the sum of the entire array.",
        "isCorrect": false
      },
      {
        "id": "sort_then_scan",
        "text": "Sort the values before examining consecutive blocks.",
        "isCorrect": false
      }
    ]
  },
  {
    "contentVersion": "algorithms-core",
    "difficulty": "intro",
    "id": "alg-contrast-sliding-window-prefix-recognize-002",
    "learningStage": "foundations",
    "primarySkillAtomId": "recognize_static_range_query_signal",
    "secondarySkillAtomIds": [
      "independent_range_queries",
      "prefix_preprocessing_reuse"
    ],
    "type": "single_choice",
    "prompt": "An immutable array is followed by many queries, each supplying unrelated left and right indexes and asking for the sum of that range. Which strategy best matches the contract?",
    "feedbackModel": {
      "decisionSignal": "The required ranges are externally specified and may appear in unrelated order.",
      "mentalModelCorrection": "Prefix sums are designed for reusable static range evaluation. A single moving window does not naturally represent arbitrary independent queries.",
      "mistakeTypes": [
        "query_contract_mismatch"
      ],
      "nextAction": "Determine whether boundaries are generated by one traversal or supplied independently.",
      "result": "diagnostic"
    },
    "options": [
      {
        "id": "prefix_sums",
        "text": "Precompute cumulative sums and answer every supplied range independently.",
        "isCorrect": true
      },
      {
        "id": "single_window",
        "text": "Maintain one active range and move it only from left to right across all queries.",
        "isCorrect": false
      },
      {
        "id": "best_range",
        "text": "Return the largest range sum instead of answering each query.",
        "isCorrect": false
      },
      {
        "id": "sort_queries_only",
        "text": "Sort the query endpoints and ignore their original order.",
        "isCorrect": false
      }
    ]
  },
  {
    "contentVersion": "algorithms-core",
    "difficulty": "intro",
    "id": "alg-contrast-sliding-window-prefix-recognize-003",
    "learningStage": "foundations",
    "primarySkillAtomId": "reject_subarray_keyword_matching",
    "secondarySkillAtomIds": [
      "problem_contract_analysis",
      "strategy_precondition_analysis"
    ],
    "type": "single_choice",
    "prompt": "A prompt contains the word subarray. What can you conclude from that fact alone?",
    "feedbackModel": {
      "decisionSignal": "Subarray describes the shape of a candidate result, not the complete algorithmic mechanism.",
      "mentalModelCorrection": "Contiguity is compatible with several patterns. The task may ask for one moving optimum, an exact range, many queries, or a different relationship between boundaries.",
      "mistakeTypes": [
        "keyword_pattern_matching"
      ],
      "nextAction": "After identifying contiguity, inspect how candidate ranges are generated and what output is required.",
      "result": "diagnostic"
    },
    "options": [
      {
        "id": "contiguous_only",
        "text": "The selected elements must be contiguous, but the correct strategy still depends on the objective and access contract.",
        "isCorrect": true
      },
      {
        "id": "always_window",
        "text": "The problem must use sliding window.",
        "isCorrect": false
      },
      {
        "id": "always_prefix",
        "text": "The problem must use prefix sums.",
        "isCorrect": false
      },
      {
        "id": "always_two_pointers",
        "text": "The problem must use opposite-end two pointers.",
        "isCorrect": false
      }
    ]
  },
  {
    "contentVersion": "algorithms-core",
    "difficulty": "intro",
    "id": "alg-contrast-sliding-window-prefix-recognize-004",
    "learningStage": "foundations",
    "primarySkillAtomId": "reject_sum_keyword_matching",
    "secondarySkillAtomIds": [
      "aggregate_signal_analysis",
      "output_contract_analysis"
    ],
    "type": "single_choice",
    "prompt": "A task asks about sums of contiguous ranges. Why is that not enough to choose prefix sums immediately?",
    "feedbackModel": {
      "decisionSignal": "The aggregate type is only one part of strategy selection.",
      "mentalModelCorrection": "Prefix sums become valuable when cumulative preprocessing is reused. A sum objective alone does not establish that reuse contract.",
      "mistakeTypes": [
        "aggregate_keyword_matching"
      ],
      "nextAction": "Separate what is aggregated from how candidate ranges are requested.",
      "result": "diagnostic"
    },
    "options": [
      {
        "id": "range_access_matters",
        "text": "The task may require one rolling range, one direct answer, or many independent queries, and those contracts favor different approaches.",
        "isCorrect": true
      },
      {
        "id": "prefixes_cannot_sum",
        "text": "Prefix sums cannot represent sums of contiguous ranges.",
        "isCorrect": false
      },
      {
        "id": "window_always_better",
        "text": "Sliding window is always better whenever ranges overlap.",
        "isCorrect": false
      },
      {
        "id": "sums_require_sorting",
        "text": "All sum problems require the values to be sorted first.",
        "isCorrect": false
      }
    ]
  },
  {
    "contentVersion": "algorithms-core",
    "difficulty": "core",
    "id": "alg-contrast-sliding-window-prefix-recognize-005",
    "learningStage": "foundations",
    "primarySkillAtomId": "distinguish_moving_range_from_queries",
    "secondarySkillAtomIds": [
      "rolling_range_state",
      "independent_query_state"
    ],
    "type": "solution_comparison",
    "prompt": "Requirement A asks for the best value among all consecutive length-k ranges. Requirement B supplies 50,000 arbitrary ranges and asks for one answer per range. Which comparison is correct?",
    "feedbackModel": {
      "decisionSignal": "A searches neighboring candidates in one traversal; B evaluates externally specified ranges.",
      "mentalModelCorrection": "The decisive contrast is not contiguity or aggregate type, but one evolving range versus many independent range requests.",
      "mistakeTypes": [
        "strategy_contrast_mismatch"
      ],
      "nextAction": "Classify the source of the range boundaries before choosing the representation.",
      "result": "diagnostic"
    },
    "options": [
      {
        "id": "window_a_prefix_b",
        "text": "A naturally fits a rolling window, while B naturally fits reusable prefix preprocessing.",
        "isCorrect": true
      },
      {
        "id": "prefix_a_window_b",
        "text": "A requires prefix sums, while B requires one moving window.",
        "isCorrect": false
      },
      {
        "id": "window_both",
        "text": "Both require sliding window because every result concerns a contiguous range.",
        "isCorrect": false
      },
      {
        "id": "prefix_both",
        "text": "Both require prefix sums because every result uses an aggregate.",
        "isCorrect": false
      }
    ]
  },
  {
    "contentVersion": "algorithms-core",
    "difficulty": "core",
    "id": "alg-contrast-sliding-window-prefix-recognize-006",
    "learningStage": "foundations",
    "primarySkillAtomId": "recognize_online_window_contract",
    "secondarySkillAtomIds": [
      "online_processing",
      "current_window_output"
    ],
    "type": "single_choice",
    "prompt": "Values arrive continuously, and after each arrival the system must report a statistic for the latest k values. Which high-level signal is strongest?",
    "feedbackModel": {
      "decisionSignal": "The answer concerns the current suffix-like range and must be produced before the full input is known.",
      "mentalModelCorrection": "Online expiration and arrival are strong rolling-window signals. Static prefix-query preprocessing assumes a reusable completed prefix history.",
      "mistakeTypes": [
        "online_contract_mismatch"
      ],
      "nextAction": "Ask whether each answer must be produced as the input evolves.",
      "result": "diagnostic"
    },
    "options": [
      {
        "id": "online_evolving_range",
        "text": "One active contiguous range evolves online as new values arrive and old values expire.",
        "isCorrect": true
      },
      {
        "id": "static_query_batch",
        "text": "All query boundaries are known before preprocessing begins.",
        "isCorrect": false
      },
      {
        "id": "global_sort_order",
        "text": "The complete input must be sorted before any answer is produced.",
        "isCorrect": false
      },
      {
        "id": "independent_subsets",
        "text": "Each answer concerns an arbitrary non-contiguous subset.",
        "isCorrect": false
      }
    ]
  },
  {
    "contentVersion": "algorithms-core",
    "difficulty": "core",
    "id": "alg-contrast-sliding-window-prefix-recognize-007",
    "learningStage": "foundations",
    "primarySkillAtomId": "recognize_candidate_window_optimization",
    "secondarySkillAtomIds": [
      "best_contiguous_range",
      "evolving_candidate_set"
    ],
    "type": "single_choice",
    "prompt": "A function must examine a sequence of overlapping candidate ranges and return only the best candidate. Which feature most strongly favors rolling state?",
    "feedbackModel": {
      "decisionSignal": "Rolling state is valuable when consecutive candidates share most of their content.",
      "mentalModelCorrection": "One output does not automatically imply sliding window. The key is reusable incremental state between ordered neighboring candidates.",
      "mistakeTypes": [
        "weak_strategy_signal"
      ],
      "nextAction": "Identify what changes between one candidate range and the next.",
      "result": "diagnostic"
    },
    "options": [
      {
        "id": "neighboring_candidates",
        "text": "Each next candidate can be derived from the previous candidate by updating boundary contributions.",
        "isCorrect": true
      },
      {
        "id": "sum_word",
        "text": "The prompt contains the word sum.",
        "isCorrect": false
      },
      {
        "id": "array_input",
        "text": "The input is stored in an array.",
        "isCorrect": false
      },
      {
        "id": "one_output",
        "text": "The function returns exactly one value, regardless of how candidates relate.",
        "isCorrect": false
      }
    ]
  },
  {
    "contentVersion": "algorithms-core",
    "difficulty": "core",
    "id": "alg-contrast-sliding-window-prefix-recognize-008",
    "learningStage": "foundations",
    "primarySkillAtomId": "recognize_prefix_reuse_contract",
    "secondarySkillAtomIds": [
      "static_input",
      "repeated_range_answers"
    ],
    "type": "single_choice",
    "prompt": "Which combination most strongly suggests prefix preprocessing?",
    "feedbackModel": {
      "decisionSignal": "One preprocessing pass can be reused across many independent reads of unchanged data.",
      "mentalModelCorrection": "Prefix sums are a static preprocessing trade-off. Their value comes from repeated reuse, not simply from working with ranges.",
      "mistakeTypes": [
        "preprocessing_signal_mismatch"
      ],
      "nextAction": "Check whether the data remains unchanged while many range answers are requested.",
      "result": "diagnostic"
    },
    "options": [
      {
        "id": "static_many_queries",
        "text": "The input is static, many range answers are required, and query boundaries are independently specified.",
        "isCorrect": true
      },
      {
        "id": "stream_latest_window",
        "text": "Values stream in and only the latest fixed-size range matters.",
        "isCorrect": false
      },
      {
        "id": "single_best_window",
        "text": "Only the best among consecutive neighboring windows is required.",
        "isCorrect": false
      },
      {
        "id": "mutable_frequent_updates",
        "text": "Array values change between every query, but no update-aware structure is available.",
        "isCorrect": false
      }
    ]
  },
  {
    "contentVersion": "algorithms-core",
    "difficulty": "core",
    "id": "alg-contrast-sliding-window-prefix-recognize-009",
    "learningStage": "foundations",
    "primarySkillAtomId": "recognize_single_exact_range_contract",
    "secondarySkillAtomIds": [
      "single_query_analysis",
      "avoid_forced_pattern_choice"
    ],
    "type": "single_choice",
    "prompt": "The input includes one array and one exact range [left, right]. The function must return that range's sum once. Which conclusion is best?",
    "feedbackModel": {
      "decisionSignal": "There is no moving candidate sequence and no stated repeated-query workload.",
      "mentalModelCorrection": "A contrast topic must still allow the answer that neither technique is justified by the current contract.",
      "mistakeTypes": [
        "forced_pattern_selection"
      ],
      "nextAction": "Do not choose preprocessing or rolling state without identifying what work they reuse.",
      "result": "diagnostic"
    },
    "options": [
      {
        "id": "neither_automatic",
        "text": "Neither sliding window nor full prefix preprocessing is automatically required; the direct workload and surrounding constraints must be considered.",
        "isCorrect": true
      },
      {
        "id": "always_window",
        "text": "Sliding window is mandatory because the range is contiguous.",
        "isCorrect": false
      },
      {
        "id": "always_prefix",
        "text": "Prefix sums are mandatory because the result is a range sum.",
        "isCorrect": false
      },
      {
        "id": "both_required",
        "text": "The function must first build prefixes and then slide over the requested range.",
        "isCorrect": false
      }
    ]
  },
  {
    "contentVersion": "algorithms-core",
    "difficulty": "core",
    "id": "alg-contrast-sliding-window-prefix-recognize-010",
    "learningStage": "foundations",
    "primarySkillAtomId": "prioritize_contract_before_complexity",
    "secondarySkillAtomIds": [
      "correctness_before_complexity",
      "range_access_contract"
    ],
    "type": "solution_comparison",
    "prompt": "A reviewer compares sliding window and prefix sums only by saying that both can run in O(n). What essential analysis is missing?",
    "feedbackModel": {
      "decisionSignal": "Asymptotic costs do not determine whether a strategy satisfies the required access and output contract.",
      "mentalModelCorrection": "Strategy comparison begins with what state must be maintained and what answers must be produced. Complexity comes after suitability.",
      "mistakeTypes": [
        "complexity_before_contract"
      ],
      "nextAction": "Describe the query, update, and output contracts before comparing Big-O.",
      "result": "diagnostic"
    },
    "options": [
      {
        "id": "required_workload",
        "text": "Whether the task maintains one evolving range or answers independently requested ranges.",
        "isCorrect": true
      },
      {
        "id": "variable_names",
        "text": "Whether the implementations use variables named left and right.",
        "isCorrect": false
      },
      {
        "id": "language_choice",
        "text": "Whether the code is written in JavaScript or Python.",
        "isCorrect": false
      },
      {
        "id": "array_values",
        "text": "Whether the first array value is larger than the last.",
        "isCorrect": false
      }
    ]
  },
  {
    "contentVersion": "algorithms-core",
    "difficulty": "core",
    "id": "alg-contrast-sliding-window-prefix-recognize-011",
    "learningStage": "foundations",
    "primarySkillAtomId": "distinguish_query_order_requirements",
    "secondarySkillAtomIds": [
      "monotonic_range_traversal",
      "arbitrary_query_order"
    ],
    "type": "strategy_choice",
    "prompt": "A list of requested ranges may jump from [900, 950] to [3, 20] and then to [500, 700]. What does this access pattern imply?",
    "feedbackModel": {
      "decisionSignal": "The requested boundaries are not monotonic and do not preserve one current range.",
      "mentalModelCorrection": "Sliding-window reuse depends on controlled neighboring movement. Arbitrary jumps favor a representation that answers each range independently.",
      "mistakeTypes": [
        "range_access_pattern_mismatch"
      ],
      "nextAction": "Inspect whether query boundaries evolve monotonically or reset independently.",
      "result": "diagnostic"
    },
    "options": [
      {
        "id": "prefix_friendly",
        "text": "The ranges are independent, so reusable prefix state is more natural than one forward-only rolling range.",
        "isCorrect": true
      },
      {
        "id": "window_friendly",
        "text": "The requests naturally form one left-to-right sliding-window traversal.",
        "isCorrect": false
      },
      {
        "id": "same_range",
        "text": "All requests should be treated as one continuously expanding range.",
        "isCorrect": false
      },
      {
        "id": "sort_input",
        "text": "The array values must be sorted before answering the queries.",
        "isCorrect": false
      }
    ]
  },
  {
    "contentVersion": "algorithms-core",
    "difficulty": "advanced",
    "id": "alg-contrast-sliding-window-prefix-recognize-012",
    "learningStage": "foundations",
    "primarySkillAtomId": "recognize_output_cardinality_signal",
    "secondarySkillAtomIds": [
      "best_window_output",
      "per_query_output"
    ],
    "type": "solution_comparison",
    "prompt": "Two tasks inspect the same array. Task A returns one best contiguous range. Task B returns one answer for every supplied range query. Which observation is strategically relevant?",
    "feedbackModel": {
      "decisionSignal": "The tasks require different relationships between candidate ranges and returned results.",
      "mentalModelCorrection": "Input shape alone does not determine the strategy. Optimization over candidates differs from independently answering every query.",
      "mistakeTypes": [
        "output_contract_mismatch"
      ],
      "nextAction": "Count what must be returned and identify who chooses each range boundary.",
      "result": "diagnostic"
    },
    "options": [
      {
        "id": "output_shapes_differ",
        "text": "A performs candidate optimization, while B must preserve the complete mapping from each query to its answer.",
        "isCorrect": true
      },
      {
        "id": "same_array_same_strategy",
        "text": "Both must use the same strategy because their input type is identical.",
        "isCorrect": false
      },
      {
        "id": "one_output_prefix",
        "text": "A requires prefix sums because it returns one value.",
        "isCorrect": false
      },
      {
        "id": "many_outputs_window",
        "text": "B requires sliding window because it returns many values.",
        "isCorrect": false
      }
    ]
  },
  {
    "contentVersion": "algorithms-core",
    "difficulty": "advanced",
    "id": "alg-contrast-sliding-window-prefix-recognize-013",
    "learningStage": "foundations",
    "primarySkillAtomId": "identify_strategy_from_state_lifecycle",
    "secondarySkillAtomIds": [
      "ephemeral_window_state",
      "persistent_prefix_state"
    ],
    "type": "single_choice",
    "prompt": "Which state-lifecycle description correctly contrasts the two strategies?",
    "feedbackModel": {
      "decisionSignal": "The strategies differ in whether historical boundary state is retained for future independent access.",
      "mentalModelCorrection": "A rolling window updates ephemeral current-range state. Prefix preprocessing stores cumulative state indexed by boundary.",
      "mistakeTypes": [
        "state_lifecycle_mismatch"
      ],
      "nextAction": "Ask which historical states must remain available after the scan passes them.",
      "result": "diagnostic"
    },
    "options": [
      {
        "id": "window_ephemeral_prefix_persistent",
        "text": "Sliding window maintains state for one current range, while prefix sums retain cumulative states for many boundaries.",
        "isCorrect": true
      },
      {
        "id": "window_all_ranges_prefix_one",
        "text": "Sliding window stores every previous range, while prefix sums remember only the current range.",
        "isCorrect": false
      },
      {
        "id": "both_same_state",
        "text": "Both strategies maintain exactly one identical scalar with the same meaning.",
        "isCorrect": false
      },
      {
        "id": "prefix_online_expiration",
        "text": "Prefix sums automatically remove expired values from one active window.",
        "isCorrect": false
      }
    ]
  },
  {
    "contentVersion": "algorithms-core",
    "difficulty": "advanced",
    "id": "alg-contrast-sliding-window-prefix-recognize-014",
    "learningStage": "foundations",
    "primarySkillAtomId": "justify_sliding_window_vs_prefix_choice",
    "secondarySkillAtomIds": [
      "strategy_justification",
      "contract_first_reasoning"
    ],
    "type": "solution_comparison",
    "prompt": "Which explanation best distinguishes sliding window from prefix sums at the strategy-selection stage?",
    "feedbackModel": {
      "decisionSignal": "A strong justification connects the strategy to state evolution and the range-access contract.",
      "mentalModelCorrection": "The contrast is not based on isolated keywords. It is based on whether one current range evolves or many static boundary pairs must remain queryable.",
      "mistakeTypes": [
        "weak_strategy_justification"
      ],
      "nextAction": "Justify the choice using state lifecycle, boundary source, and output requirements.",
      "result": "diagnostic"
    },
    "options": [
      {
        "id": "complete_contrast",
        "text": "Use rolling window when one contiguous range evolves and neighboring states can be updated incrementally; use prefix preprocessing when static cumulative state must answer independently specified ranges.",
        "isCorrect": true
      },
      {
        "id": "sum_contrast",
        "text": "Use prefix sums for sum problems and sliding window for every other aggregate.",
        "isCorrect": false
      },
      {
        "id": "subarray_contrast",
        "text": "Use sliding window for subarrays and prefix sums for arrays.",
        "isCorrect": false
      },
      {
        "id": "big_o_contrast",
        "text": "Choose whichever approach is described with the lower Big-O, without first checking the query contract.",
        "isCorrect": false
      }
    ]
  }
] as const satisfies readonly AlgorithmQuestion[];
