export const ROUTES = {
  HOME: "Home",
  SELECT_TRACK: "select_track",
  PRACTICE_HUB: "PracticeHub",
  TOPIC_ROADMAP: "TopicRoadmap",
  EXAM: "Exam",
  EXAM_REVIEW: "ExamReview",
  RESULT: "Result",
  ANSWER_REVIEW: "AnswerReview",
  PRACTICE_SETUP: "PracticeSetup",
  PRACTICE_SESSION: "PracticeSession",
  ALGORITHMS_INTERVIEW_SIMULATION: "AlgorithmsInterviewSimulation",
  ALGORITHMS_INTERVIEW_SIMULATION_SUMMARY: "AlgorithmsInterviewSimulationSummary",
  ALGORITHMS_INTERVIEW_SIMULATION_REVIEW: "AlgorithmsInterviewSimulationReview",
  MISTAKES_REVIEW: "MistakesReview",
} as const;
