export const ROUTES = {
  HOME: "Home",
  APPEARANCE_SETTINGS: "AppearanceSettings",
  LEGAL_INFORMATION: "LegalInformation",
  LANGUAGE_SETTINGS: "LanguageSettings",
  NOTIFICATION_SETTINGS: "NotificationSettings",
  YOUR_DATA: "YourData",
  SELECT_TRACK: "select_track",
  PRACTICE_HUB: "PracticeHub",
  ALGORITHMS_SCOPE_SELECTION: "AlgorithmsScopeSelection",
  TOPIC_ROADMAP: "TopicRoadmap",
  EXAM: "Exam",
  EXAM_REVIEW: "ExamReview",
  RESULT: "Result",
  ANSWER_REVIEW: "AnswerReview",
  PRACTICE_SETUP: "PracticeSetup",
  PRACTICE_SESSION: "PracticeSession",
  ALGORITHMS_INTERVIEW_SIMULATION: "AlgorithmsInterviewSimulation",
  ALGORITHMS_INTERVIEW_SIMULATION_SUMMARY: "AlgorithmsInterviewSimulationSummary",
  ALGORITHMS_INTERVIEW_SIMULATION_REVIEW: "AlgorithmsInterviewSimulationReview",
  MISTAKES_REVIEW: "MistakesReview",
} as const;
