import type { ReviewQueueEntry, TrackId } from "../../domain";
import { STORAGE_KEYS } from "../keys";
import { readStoredJson, removeStoredValue, writeStoredJson } from "../storageCodec";
import { isReviewQueueEntry } from "./trainingModelGuards";
import type { StorageRepositoryResult } from "./result";
const isIds = (value: unknown): value is string[] => Array.isArray(value) && value.every((id) => typeof id === "string");
export async function getReviewQueueItems(): Promise<StorageRepositoryResult<ReviewQueueEntry[]>> { const ids = readStoredJson(STORAGE_KEYS.REVIEW_INDEX, isIds) ?? []; return { ok: true, value: ids.map((id) => { const entry = readStoredJson(STORAGE_KEYS.reviewEntry(id), isReviewQueueEntry); if (!entry) throw new Error(`Review index references missing entry ${id}.`); return entry; }) }; }
export async function addReviewQueueItems(items: ReviewQueueEntry[]): Promise<StorageRepositoryResult<ReviewQueueEntry[]>> { const current = (await getReviewQueueItems()).value; const byIdentity = new Map(current.map((entry) => [`${entry.trackId}:${entry.sourceItem.itemId}`, entry])); for (const item of items) byIdentity.set(`${item.trackId}:${item.sourceItem.itemId}`, item); const values = [...byIdentity.values()]; values.forEach((item) => writeStoredJson(STORAGE_KEYS.reviewEntry(item.id), item)); writeStoredJson(STORAGE_KEYS.REVIEW_INDEX, values.map((item) => item.id)); return { ok: true, value: values }; }
export async function saveReviewQueueItems(items: ReviewQueueEntry[]): Promise<StorageRepositoryResult<ReviewQueueEntry[]>> { return addReviewQueueItems(items); }
export async function getDueReviewQueueItems(trackId: TrackId, now: string): Promise<StorageRepositoryResult<ReviewQueueEntry[]>> { return { ok: true, value: (await getReviewQueueItems()).value.filter((entry) => entry.trackId === trackId && entry.dueAt <= now).sort((a,b) => a.dueAt.localeCompare(b.dueAt) || a.createdAt.localeCompare(b.createdAt)) }; }
export async function removeReviewQueueItem(trackId: TrackId, itemId: string): Promise<StorageRepositoryResult<ReviewQueueEntry[]>> { const values = (await getReviewQueueItems()).value.filter((entry) => entry.trackId !== trackId || entry.sourceItem.itemId !== itemId); writeStoredJson(STORAGE_KEYS.REVIEW_INDEX, values.map((entry) => entry.id)); return { ok: true, value: values }; }
export async function clearReviewQueueItems(): Promise<void> { const ids = (await getReviewQueueItems()).value.map((entry) => entry.id); ids.forEach((id) => removeStoredValue(STORAGE_KEYS.reviewEntry(id))); removeStoredValue(STORAGE_KEYS.REVIEW_INDEX); }
