import type { TrainingAttempt } from "../../domain";
import { STORAGE_KEYS } from "../keys";
import { readCanonicalJson, removeCanonicalValue, writeCanonicalJson } from "./canonicalRecordCodec";
import { isTrainingAttempt } from "./trainingModelGuards";
import type { StorageRepositoryResult } from "./result";
const isIds = (value: unknown): value is string[] => Array.isArray(value) && value.every((id) => typeof id === "string");
export async function getTrainingAttempts(): Promise<StorageRepositoryResult<TrainingAttempt<unknown>[]>> { const ids = readCanonicalJson(STORAGE_KEYS.TRAINING_ATTEMPT_INDEX, isIds) ?? []; return { ok: true, value: ids.map((id) => { const value = readCanonicalJson(STORAGE_KEYS.trainingAttempt(id), isTrainingAttempt); if (!value) throw new Error(`Attempt index references missing attempt ${id}.`); return value; }) }; }
export async function addTrainingAttempt(attempt: TrainingAttempt<unknown>): Promise<StorageRepositoryResult<TrainingAttempt<unknown>>> { if (!isTrainingAttempt(attempt)) throw new Error("Training attempt is invalid."); const old = readCanonicalJson(STORAGE_KEYS.trainingAttempt(attempt.id), isTrainingAttempt); if (old && JSON.stringify(old) !== JSON.stringify(attempt)) throw new Error(`Attempt ${attempt.id} is immutable.`); if (!old) writeCanonicalJson(STORAGE_KEYS.trainingAttempt(attempt.id), attempt); const ids = readCanonicalJson(STORAGE_KEYS.TRAINING_ATTEMPT_INDEX, isIds) ?? []; if (!ids.includes(attempt.id)) writeCanonicalJson(STORAGE_KEYS.TRAINING_ATTEMPT_INDEX, [attempt.id, ...ids]); return { ok: true, value: old ?? attempt }; }
export async function clearTrainingAttempts(): Promise<void> { const ids = readCanonicalJson(STORAGE_KEYS.TRAINING_ATTEMPT_INDEX, isIds) ?? []; ids.forEach((id) => removeCanonicalValue(STORAGE_KEYS.trainingAttempt(id))); removeCanonicalValue(STORAGE_KEYS.TRAINING_ATTEMPT_INDEX); }
