// Planning target: this file should contain questions about recognizing the high-level contrast between binary search and linear scan:
// sorted indexed input; monotonic predicate; answer-space feasible/infeasible split;
// versus arbitrary unsorted data where only linear inspection is justified.
// It should diagnose mistakes such as choosing binary search only because the prompt says "search",
// choosing linear scan despite a clear sorted/monotonic half-discard signal,
// assuming every numeric answer is binary-searchable,
// or failing to name what makes binary search legal.
// Target question count: 16.
// Prefer single_choice, strategy_choice, solution_comparison, and mistake-review style items.
// Avoid detailed boundary mechanics; this file is about recognition and legality.
type RecognizeQuestionSpec = {
  id: string;
  title: string;
  difficulty: "intro" | "easy" | "medium";
  primarySkillAtomId: string;
  patternVariantId: string;
  mistakeType: string;
  prompt: string;
  correction: string;
  nextAction: string;
  correctAnswer: string;
  correctText: string;
  wrongOptions: readonly { id: string; text: string; explanation: string }[];
  itemType: "single_choice" | "strategy_choice" | "solution_comparison" | "common_mistake_diagnosis";
  expectedApproachIds?: readonly string[];
  acceptableApproachIds?: readonly string[];
  rejectedApproachIds?: readonly string[];
  constraintSignal?: string;
  reasonSignal?: string;
};

const makeRecognizeQuestion = (spec: RecognizeQuestionSpec) => ({
  contentVersion: "algorithms-core",
  difficulty: spec.difficulty,
  feedbackModel: {
    decisionSignal: spec.prompt,
    mentalModelCorrection: spec.correction,
    mistakeTypes: [spec.mistakeType],
    nextAction: spec.nextAction,
    result: "diagnostic",
    distractorExplanations: Object.fromEntries(spec.wrongOptions.map((option) => [option.id, option.explanation])),
  },
  id: spec.id,
  learningStage: "contrast_practice",
  primarySkillAtomId: spec.primarySkillAtomId,
  prompt: spec.prompt,
  roadmapNodeId: "contrast_binary_search_vs_linear_scan",
  status: "active",
  staticMicroChecks: [
    {
      correctAnswer: spec.correctAnswer,
      feedback: spec.correction,
      id: `${spec.id}-check`,
      mistakeTypes: [spec.mistakeType],
      options: [{ id: spec.correctAnswer, text: spec.correctText }, ...spec.wrongOptions],
      prompt: `For "${spec.title}", choose the strategy signal.`,
      status: "active",
      testedSkillAtomIds: [spec.primarySkillAtomId],
      type: "single_choice",
    },
  ],
  taxonomyRefs: [
    { axisId: "pattern_family", nodeId: "binary_search", role: "primary" },
    { axisId: "skill_atom", nodeId: spec.primarySkillAtomId, role: "primary" },
    { axisId: "pattern_variant", nodeId: spec.patternVariantId, role: "secondary" },
    { axisId: "mistake_type", nodeId: spec.mistakeType, role: "mistake_type" },
  ],
  title: spec.title,
  trackId: "algorithms",
  type: spec.itemType,
  ...(spec.itemType === "strategy_choice"
    ? {
        acceptableApproachIds: spec.acceptableApproachIds ?? [],
        constraintSignal: spec.constraintSignal,
        expectedApproachIds: spec.expectedApproachIds,
        reasonSignal: spec.reasonSignal,
        rejectedApproachIds: spec.rejectedApproachIds,
        responseSpec: {
          kind: "strategy_selection",
          strategies: [{ id: spec.correctAnswer, text: spec.correctText }, ...spec.wrongOptions],
        },
      }
    : {}),
  ...(spec.itemType === "solution_comparison"
    ? {
        responseSpec: {
          comparisonCriteria: ["legality signal", "candidate structure", "safe discard rule"],
          kind: "solution_comparison",
          solutions: [
            { id: spec.correctAnswer, text: spec.correctText },
            ...spec.wrongOptions.map(({ id, text }) => ({ id, text })),
          ],
        },
      }
    : {}),
});

export const recognizeContrastSignalQuestions = [
  makeRecognizeQuestion({
    id: "alg-contrast-binary-linear-recognize-001",
    title: "Recognize sorted indexed lookup",
    difficulty: "intro",
    primarySkillAtomId: "recognize_binary_search_signal",
    patternVariantId: "classic_index_search",
    mistakeType: "structure_signal_missed",
    prompt: "A sorted ascending array stores n values, and the task asks whether target exists. What is the strongest strategy signal?",
    correction: "Sorted indexed order lets a comparison with the middle value eliminate one side of the remaining indexes.",
    nextAction: "Name the ordered property that makes half-discarding legal before discussing implementation.",
    correctAnswer: "sorted_indexed",
    correctText: "Use binary search because sorted indexes let each comparison discard a half.",
    wrongOptions: [
      { id: "search_word", text: "Use binary search because the prompt says search.", explanation: "The wording names the goal, not the structural property that makes binary search correct." },
      { id: "array_always", text: "Use binary search because the input is an array.", explanation: "An array can be unsorted; indexing alone does not order values." },
    ],
    itemType: "strategy_choice",
    expectedApproachIds: ["classic_index_binary_search"],
    acceptableApproachIds: ["classic_index_binary_search"],
    rejectedApproachIds: ["linear_scan_default"],
    constraintSignal: "The array is sorted and indexable.",
    reasonSignal: "A midpoint comparison can prove one side contains no target.",
  }),
  makeRecognizeQuestion({
    id: "alg-contrast-binary-linear-recognize-002",
    title: "Recognize monotonic predicate search",
    difficulty: "easy",
    primarySkillAtomId: "monotonic_predicate_boundary",
    patternVariantId: "monotonic_predicate_recognition",
    mistakeType: "monotonic_signal_missed",
    prompt: "For increasing candidates x, feasible(x) is false, false, false, true, true, true. What makes binary search legal even though there is no array of stored values?",
    correction: "The ordered candidates have a single false-to-true boundary, so one feasibility check can eliminate a side.",
    nextAction: "Look for a one-direction feasibility transition when the search domain is an answer range.",
    correctAnswer: "monotonic_boundary",
    correctText: "The feasibility predicate is monotonic and exposes one searchable boundary.",
    wrongOptions: [
      { id: "numeric_domain", text: "Any numeric candidate range is automatically binary-searchable.", explanation: "Numeric order is necessary here, but the monotonic feasibility transition is what makes elimination safe." },
      { id: "boolean_output", text: "Any boolean result supports binary search.", explanation: "Boolean output can alternate; it must be monotonic over the ordered candidates." },
    ],
    itemType: "single_choice",
  }),
  makeRecognizeQuestion({
    id: "alg-contrast-binary-linear-recognize-003",
    title: "Recognize unsorted direct inspection",
    difficulty: "intro",
    primarySkillAtomId: "recognize_binary_search_signal",
    patternVariantId: "classic_index_search",
    mistakeType: "constraint_ignored",
    prompt: "An unsorted array contains customer IDs, and there is one membership query. Which high-level decision is justified from the stated structure?",
    correction: "Without sorted order, a midpoint does not prove either half is impossible, so direct inspection is the justified choice.",
    nextAction: "Reject binary search when no value order or monotonic predicate is supplied.",
    correctAnswer: "linear_inspection",
    correctText: "Inspect the records directly because the array has no ordered half-discard rule.",
    wrongOptions: [
      { id: "numeric_ids", text: "Use binary search because IDs are numeric.", explanation: "Numeric values do not order their positions in an unsorted array." },
      { id: "membership_binary", text: "Use binary search because membership is a search problem.", explanation: "Membership can be solved by different strategies; the structure determines legality." },
    ],
    itemType: "strategy_choice",
    expectedApproachIds: ["linear_scan_default"],
    acceptableApproachIds: ["linear_scan_default"],
    rejectedApproachIds: ["classic_index_binary_search"],
    constraintSignal: "The data is unsorted and only one query is stated.",
    reasonSignal: "No midpoint comparison can eliminate a half of arbitrary-order data.",
  }),
  makeRecognizeQuestion({
    id: "alg-contrast-binary-linear-recognize-004",
    title: "Name the legal discard signal",
    difficulty: "easy",
    primarySkillAtomId: "recognize_binary_search_signal",
    patternVariantId: "classic_index_search",
    mistakeType: "cannot_explain_why",
    prompt: "A learner can name binary search but cannot explain why its midpoint decision is safe. What explanation is required?",
    correction: "Binary search is justified only when order or monotonicity proves that all candidates on one side are impossible.",
    nextAction: "Explain the eliminated side, not just the algorithm name, before accepting the strategy.",
    correctAnswer: "discard_proof",
    correctText: "A sorted or monotonic structure proves that the discarded side cannot contain a valid answer.",
    wrongOptions: [
      { id: "half_fast", text: "It is valid because checking half the indexes is faster.", explanation: "Speed does not make an unsupported discard correct." },
      { id: "midpoint_exists", text: "It is valid because every range has a midpoint.", explanation: "A midpoint exists even when its value gives no information about either side." },
    ],
    itemType: "single_choice",
  }),
  makeRecognizeQuestion({
    id: "alg-contrast-binary-linear-recognize-005",
    title: "Separate target space from input order",
    difficulty: "medium",
    primarySkillAtomId: "binary_search_answer_feasibility_predicate",
    patternVariantId: "binary_search_on_answer",
    mistakeType: "state_model_misread",
    prompt: "The input array is unsorted, but the task has a numeric answer x. Which question determines whether binary search on x is even a candidate?",
    correction: "The answer domain must have a monotonic feasibility predicate; the fact that x is numeric is not enough.",
    nextAction: "Define what feasible(x) means and inspect whether its outcomes change direction at most once.",
    correctAnswer: "feasibility_shape",
    correctText: "Check whether feasibility over x is monotonic and creates a single boundary.",
    wrongOptions: [
      { id: "array_sorted", text: "Check only whether the original array is sorted.", explanation: "Answer-space search can be legal without a sorted input array, but it still needs monotonic feasibility." },
      { id: "answer_numeric", text: "Nothing else is needed because x is numeric.", explanation: "Numeric candidates can have arbitrary feasible and infeasible regions." },
    ],
    itemType: "single_choice",
  }),
  makeRecognizeQuestion({
    id: "alg-contrast-binary-linear-recognize-006",
    title: "Reject keyword-only selection",
    difficulty: "intro",
    primarySkillAtomId: "recognize_binary_search_signal",
    patternVariantId: "classic_index_search",
    mistakeType: "wrong_approach",
    prompt: "A prompt says ‘search for a matching record’, but gives an unsorted list and no predicate over ordered candidates. What diagnosis is correct?",
    correction: "The word search is not evidence for binary search; the input must expose ordered elimination or a monotonic boundary.",
    nextAction: "Read the data structure and constraints before reacting to search-related wording.",
    correctAnswer: "keyword_not_signal",
    correctText: "Reject binary search because the prompt provides no legal discard structure.",
    wrongOptions: [
      { id: "keyword_is_signal", text: "Choose binary search because search is in the prompt.", explanation: "Natural-language keywords do not establish sorted order or monotonicity." },
      { id: "record_lookup", text: "Choose binary search because lookup tasks always halve candidates.", explanation: "Lookup can require linear inspection when records are arbitrary-order." },
    ],
    itemType: "common_mistake_diagnosis",
  }),
  makeRecognizeQuestion({
    id: "alg-contrast-binary-linear-recognize-007",
    title: "Do not miss sorted lookup",
    difficulty: "easy",
    primarySkillAtomId: "recognize_binary_search_signal",
    patternVariantId: "classic_index_search",
    mistakeType: "monotonic_signal_missed",
    prompt: "A learner chooses a left-to-right scan for a sorted array with many indexed membership checks. Which signal did they miss?",
    correction: "Sorted indexed order supports logarithmic lookup by eliminating half of the remaining positions per query.",
    nextAction: "When a target lookup is order-preserving, compare the scan with the legal halving strategy.",
    correctAnswer: "sorted_half_discard",
    correctText: "They missed that sorted indexes allow each comparison to eliminate half the candidates.",
    wrongOptions: [
      { id: "scan_always_best", text: "They are correct because a scan is always the safest lookup.", explanation: "A scan is correct, but it is not asymptotically best when sorted order supports halving." },
      { id: "array_requires_scan", text: "They are correct because arrays must always be scanned.", explanation: "Indexable sorted arrays are a canonical binary-search structure." },
    ],
    itemType: "solution_comparison",
  }),
  makeRecognizeQuestion({
    id: "alg-contrast-binary-linear-recognize-008",
    title: "Recognize first feasible candidate",
    difficulty: "easy",
    primarySkillAtomId: "monotonic_predicate_boundary",
    patternVariantId: "monotonic_predicate_recognition",
    mistakeType: "monotonic_signal_missed",
    prompt: "For ordered capacities, every capacity below c is infeasible and every capacity at or above c is feasible. What high-level task shape is present?",
    correction: "The feasibility outcomes form a false prefix and true suffix, which is a searchable first-true boundary.",
    nextAction: "Translate ordered feasibility outcomes into the boundary the query asks you to locate.",
    correctAnswer: "first_true_boundary",
    correctText: "This is a monotonic first-true boundary, so binary search can replace a full scan.",
    wrongOptions: [
      { id: "arbitrary_boolean", text: "It is an arbitrary boolean query with no searchable structure.", explanation: "The specified false-prefix and true-suffix shape is exactly the needed structure." },
      { id: "input_membership", text: "It is ordinary membership in an unsorted input array.", explanation: "The ordered capacity domain and feasibility boundary define a different search space." },
    ],
    itemType: "strategy_choice",
    expectedApproachIds: ["monotonic_boundary_binary_search"],
    acceptableApproachIds: ["monotonic_boundary_binary_search"],
    rejectedApproachIds: ["linear_scan_default"],
    constraintSignal: "Feasibility is false below one boundary and true from that boundary onward.",
    reasonSignal: "A first-true boundary supports safe half-discarding.",
  }),
  makeRecognizeQuestion({
    id: "alg-contrast-binary-linear-recognize-009",
    title: "Distinguish arbitrary boolean output",
    difficulty: "medium",
    primarySkillAtomId: "binary_search_answer_feasibility_predicate",
    patternVariantId: "monotonic_predicate_recognition",
    mistakeType: "monotonic_assumption_invalid",
    prompt: "A predicate returns true for some candidates and false for others, but its results alternate as the candidate increases. What is the correct strategy signal?",
    correction: "Boolean output alone is insufficient; alternating results do not expose a boundary from which a half can be discarded.",
    nextAction: "Write predicate outcomes in candidate order and reject binary search when they reverse direction.",
    correctAnswer: "not_monotonic",
    correctText: "The predicate is not monotonic, so binary search is not justified by its boolean return type.",
    wrongOptions: [
      { id: "boolean_search", text: "Use binary search because the result is boolean.", explanation: "The shape of the boolean sequence, not its type, determines legality." },
      { id: "candidate_order", text: "Use binary search because the candidates are ordered numerically.", explanation: "Ordered candidates need a monotonic predicate to support elimination." },
    ],
    itemType: "single_choice",
  }),
  makeRecognizeQuestion({
    id: "alg-contrast-binary-linear-recognize-010",
    title: "Do not confuse correctness with efficiency",
    difficulty: "intro",
    primarySkillAtomId: "recognize_binary_search_signal",
    patternVariantId: "classic_index_search",
    mistakeType: "complexity_mismatch",
    prompt: "A linear scan returns the correct answer for a sorted array, but the constraints allow n = 1,000,000. What should the strategy review say?",
    correction: "Correctness and asymptotic efficiency are separate: a scan may be correct while binary search better fits large sorted input.",
    nextAction: "After checking correctness, compare growth rates against the stated input limits.",
    correctAnswer: "correct_but_slower",
    correctText: "The scan is correct, but sorted order provides a faster O(log n) lookup than O(n).",
    wrongOptions: [
      { id: "scan_invalid", text: "The scan is incorrect because sorted arrays require binary search.", explanation: "Sorted order permits binary search but does not make a linear scan incorrect." },
      { id: "same_growth", text: "Both strategies have the same asymptotic growth on an array.", explanation: "A full scan is O(n), while legal repeated halving is O(log n)." },
    ],
    itemType: "solution_comparison",
  }),
  makeRecognizeQuestion({
    id: "alg-contrast-binary-linear-recognize-011",
    title: "Check indexability as well as order",
    difficulty: "medium",
    primarySkillAtomId: "recognize_binary_search_signal",
    patternVariantId: "classic_index_search",
    mistakeType: "data_structure_mismatch",
    prompt: "Values are sorted, but the data structure only exposes the next item through a linked traversal. Which legality question remains before selecting indexed binary search?",
    correction: "Classic binary search needs efficient access to a midpoint; sorted values alone do not supply random access.",
    nextAction: "Check both ordering and the cost of reaching the midpoint in the actual data structure.",
    correctAnswer: "midpoint_access",
    correctText: "Verify that midpoint positions are efficiently indexable; sorted order alone is not enough.",
    wrongOptions: [
      { id: "sorted_sufficient", text: "Use binary search automatically because the values are sorted.", explanation: "A linked traversal may make midpoint access linear and remove the intended benefit." },
      { id: "search_word", text: "Use binary search because the task is a lookup.", explanation: "Lookup wording cannot replace the required access and order properties." },
    ],
    itemType: "single_choice",
  }),
  makeRecognizeQuestion({
    id: "alg-contrast-binary-linear-recognize-012",
    title: "Recognize a true-suffix boundary",
    difficulty: "easy",
    primarySkillAtomId: "monotonic_predicate_boundary",
    patternVariantId: "monotonic_predicate_recognition",
    mistakeType: "structure_signal_missed",
    prompt: "A sorted status list has outcomes false, false, true, true, true, and the task asks for the first accepted position. What should replace a linear scan?",
    correction: "The false-prefix and true-suffix structure lets binary search locate the first accepted position without inspecting every earlier item.",
    nextAction: "Name the boundary requested by the output contract before choosing the search strategy.",
    correctAnswer: "first_true_binary",
    correctText: "Use binary search for the first true boundary because the predicate is monotonic.",
    wrongOptions: [
      { id: "linear_only", text: "Use a linear scan because boundary tasks always require checking from the start.", explanation: "A monotonic false-prefix/true-suffix lets binary search skip the prefix safely." },
      { id: "any_true", text: "Return any true position because all true positions are equivalent.", explanation: "The task asks for the first boundary, so the output contract matters." },
    ],
    itemType: "strategy_choice",
    expectedApproachIds: ["monotonic_boundary_binary_search"],
    acceptableApproachIds: ["monotonic_boundary_binary_search"],
    rejectedApproachIds: ["linear_scan_default"],
    constraintSignal: "The predicate is false before one boundary and true from it onward.",
    reasonSignal: "The monotonic suffix supports a first-true binary search.",
  }),
  makeRecognizeQuestion({
    id: "alg-contrast-binary-linear-recognize-013",
    title: "Keep numeric target reasoning separate",
    difficulty: "medium",
    primarySkillAtomId: "binary_search_answer_feasibility_predicate",
    patternVariantId: "binary_search_on_answer",
    mistakeType: "state_model_misread",
    prompt: "A task asks for the smallest integer x satisfying a condition, but no relationship between x and condition(x) is stated. What is the correct recognition step?",
    correction: "‘Smallest numeric answer’ describes the output, not a binary-search signal; feasibility must be monotonic first.",
    nextAction: "Ask whether every larger candidate remains feasible after the first feasible candidate.",
    correctAnswer: "prove_feasibility",
    correctText: "First establish a monotonic feasibility predicate before considering binary search on x.",
    wrongOptions: [
      { id: "smallest_means_binary", text: "Use binary search because the task asks for the smallest number.", explanation: "An optimization target can be non-monotonic and may not expose a searchable boundary." },
      { id: "numeric_always", text: "Use binary search because x ranges over integers.", explanation: "Integer order alone does not make condition(x) monotonic." },
    ],
    itemType: "single_choice",
  }),
  makeRecognizeQuestion({
    id: "alg-contrast-binary-linear-recognize-014",
    title: "Identify the direct-scan case",
    difficulty: "intro",
    primarySkillAtomId: "recognize_binary_search_signal",
    patternVariantId: "classic_index_search",
    mistakeType: "wrong_approach",
    prompt: "Which case most clearly justifies a linear scan rather than binary search?",
    correction: "An arbitrary-order collection with one query and no monotonic predicate gives no safe way to eliminate a half.",
    nextAction: "Select the strategy from the strongest available structure, not from the word search or target type.",
    correctAnswer: "arbitrary_one_query",
    correctText: "An arbitrary-order collection with one query and no monotonic predicate.",
    wrongOptions: [
      { id: "sorted_membership", text: "A sorted indexed array with a target membership query.", explanation: "Sorted indexed membership is a direct classic binary-search signal." },
      { id: "first_feasible", text: "An ordered candidate domain with a false-prefix/true-suffix feasibility rule.", explanation: "A monotonic boundary is also a direct binary-search signal." },
    ],
    itemType: "strategy_choice",
    expectedApproachIds: ["linear_scan_default"],
    acceptableApproachIds: ["linear_scan_default"],
    rejectedApproachIds: ["classic_index_binary_search", "monotonic_boundary_binary_search"],
    constraintSignal: "No order or monotonicity links a midpoint result to either side.",
    reasonSignal: "Direct inspection is required when every position can still contain the target.",
  }),
  makeRecognizeQuestion({
    id: "alg-contrast-binary-linear-recognize-015",
    title: "Contrast stored values with answer candidates",
    difficulty: "medium",
    primarySkillAtomId: "recognize_binary_search_signal",
    patternVariantId: "classic_index_search",
    mistakeType: "concept_boundary_confused",
    prompt: "Which statement correctly distinguishes classic lookup from binary search over an answer space?",
    correction: "Classic lookup relies on ordered stored values; answer-space search relies on monotonic feasibility over candidate answers.",
    nextAction: "Identify whether the midpoint is an input index or an answer candidate, then name the corresponding structure.",
    correctAnswer: "two_legal_signals",
    correctText: "Stored order supports classic lookup; monotonic feasibility supports answer-space search.",
    wrongOptions: [
      { id: "same_signal", text: "They are legal for the same reason: the target is numeric.", explanation: "The two variants use different structures even when both involve numeric comparisons." },
      { id: "word_signal", text: "They are legal whenever the prompt uses search terminology.", explanation: "Prompt wording does not establish either stored order or feasibility monotonicity." },
    ],
    itemType: "solution_comparison",
  }),
  makeRecognizeQuestion({
    id: "alg-contrast-binary-linear-recognize-016",
    title: "Diagnose structure-free binary search",
    difficulty: "medium",
    primarySkillAtomId: "recognize_binary_search_signal",
    patternVariantId: "classic_index_search",
    mistakeType: "cannot_explain_why",
    prompt: "A code review contains a binary-search loop, but the input is arbitrary-order and the author cannot state what makes a discarded half impossible. What is the correct review outcome?",
    correction: "Without a stated order or monotonicity invariant, the binary-search loop is an unsupported optimization rather than a justified strategy.",
    nextAction: "Require the structural discard invariant or replace the strategy with direct inspection.",
    correctAnswer: "reject_unsupported_search",
    correctText: "Reject the binary-search choice until a sorted or monotonic discard invariant is established.",
    wrongOptions: [
      { id: "loop_is_enough", text: "Accept it because the loop halves its numeric bounds.", explanation: "Halving bounds is only correct when the removed side is proven impossible." },
      { id: "faster_is_enough", text: "Accept it because O(log n) is always preferable to O(n).", explanation: "An asymptotically smaller but invalid method cannot be accepted." },
    ],
    itemType: "common_mistake_diagnosis",
  }),
];
