export type LegalLocale = "en" | "pl";

/** Runtime retention limit for reports that have not been confirmed by the server. */
export const localReportOutboxRetentionDays = 30 as const;

// Edit these values before publishing. Legal documents intentionally contain no runtime validation.
export const legalVariables = {
  documentVersion: { en: "2026-09-05", pl: "2026-09-05" },
  premiumCheckoutEnabled: false,
  terms: {
    adrEntity: { en: "[TO BE COMPLETED: adrEntity]", pl: "[DO UZUPEŁNIENIA: adrEntity]" },
    adrPosition: { en: "[TO BE COMPLETED: adrPosition]", pl: "[DO UZUPEŁNIENIA: adrPosition]" },
    competentCourts: { en: "[TO BE COMPLETED: competentCourts]", pl: "[DO UZUPEŁNIENIA: competentCourts]" },
    complaintEmail: { en: "[TO BE COMPLETED: complaintEmail]", pl: "[DO UZUPEŁNIENIA: complaintEmail]" },
    distributionTerritories: { en: "[TO BE COMPLETED: distributionTerritories]", pl: "[DO UZUPEŁNIENIA: distributionTerritories]" },
    effectiveDate: { en: "[TO BE COMPLETED: effectiveDate]", pl: "[DO UZUPEŁNIENIA: effectiveDate]" },
    governingLaw: { en: "[TO BE COMPLETED: governingLaw]", pl: "[DO UZUPEŁNIENIA: governingLaw]" },
    merchantOfRecord: { en: "Apple App Store", pl: "Apple App Store" },
    minimumUserAge: { en: "18", pl: "18" },
    minimumUserAgeScope: { en: "[TO BE COMPLETED: minimumUserAgeScope]", pl: "[DO UZUPEŁNIENIA: minimumUserAgeScope]" },
    operatorBusinessForm: { en: "[TO BE COMPLETED: operatorBusinessForm]", pl: "[DO UZUPEŁNIENIA: operatorBusinessForm]" },
    operatorEmail: { en: "[TO BE COMPLETED: operatorEmail]", pl: "[DO UZUPEŁNIENIA: operatorEmail]" },
    operatorLegalName: { en: "[TO BE COMPLETED: operatorLegalName]", pl: "[DO UZUPEŁNIENIA: operatorLegalName]" },
    operatorPhone: { en: "[TO BE COMPLETED: operatorPhone]", pl: "[DO UZUPEŁNIENIA: operatorPhone]" },
    operatorRegisteredAddress: { en: "[TO BE COMPLETED: operatorRegisteredAddress]", pl: "[DO UZUPEŁNIENIA: operatorRegisteredAddress]" },
    operatorRegistrationNumber: { en: "[TO BE COMPLETED: operatorRegistrationNumber]", pl: "[DO UZUPEŁNIENIA: operatorRegistrationNumber]" },
    operatorTaxIdentifier: { en: "[TO BE COMPLETED: operatorTaxIdentifier]", pl: "[DO UZUPEŁNIENIA: operatorTaxIdentifier]" },
    premiumBillingPeriod: { en: "one month", pl: "jeden miesiąc" },
    premiumPriceIncludingTaxes: { en: "[TO BE COMPLETED: premiumPriceIncludingTaxes]", pl: "[DO UZUPEŁNIENIA: premiumPriceIncludingTaxes]" },
    premiumProductIdentifier: { en: "com.lkurczab.patternly.premium.monthly", pl: "com.lkurczab.patternly.premium.monthly" },
    premiumProductName: { en: "Patternly Premium", pl: "Patternly Premium" },
    premiumRenewalPriceIncludingTaxes: { en: "[TO BE COMPLETED: premiumRenewalPriceIncludingTaxes]", pl: "[DO UZUPEŁNIENIA: premiumRenewalPriceIncludingTaxes]" },
    premiumServiceScope: { en: "[TO BE COMPLETED: premiumServiceScope]", pl: "[DO UZUPEŁNIENIA: premiumServiceScope]" },
    supportCommitment: { en: "[TO BE COMPLETED: supportCommitment]", pl: "[DO UZUPEŁNIENIA: supportCommitment]" },
    technicalRequirements: { en: "[TO BE COMPLETED: technicalRequirements]", pl: "[DO UZUPEŁNIENIA: technicalRequirements]" },
    withdrawalEmail: { en: "[TO BE COMPLETED: withdrawalEmail]", pl: "[DO UZUPEŁNIENIA: withdrawalEmail]" },
  },
  privacy: {
    activeCloudProcessors: { en: "[TO BE COMPLETED: activeCloudProcessors]", pl: "[DO UZUPEŁNIENIA: activeCloudProcessors]" },
    activeIndependentRecipients: { en: "[TO BE COMPLETED: activeIndependentRecipients]", pl: "[DO UZUPEŁNIENIA: activeIndependentRecipients]" },
    anonymousReportRetentionDays: { en: "30", pl: "30" },
    backupPurgeDisclosure: { en: "Firestore point-in-time recovery retains database versions for up to 7 days. Patternly does not maintain an additional scheduled Firestore backup. Expired or deleted data may therefore remain recoverable within the protected PITR window and is no longer recoverable after that window expires.", pl: "Odzyskiwanie Firestore do punktu w czasie przechowuje wersje bazy maksymalnie przez 7 dni. Patternly nie utrzymuje dodatkowej harmonogramowej kopii zapasowej Firestore. Wygasłe lub usunięte dane mogą więc pozostać możliwe do odzyskania w chronionym oknie PITR, a po jego upływie nie są już możliwe do odzyskania." },
    clipboardRecoveryCodeRetentionMinutes: { en: "[TO BE COMPLETED: clipboardRecoveryCodeRetentionMinutes]", pl: "[DO UZUPEŁNIENIA: clipboardRecoveryCodeRetentionMinutes]" },
    completedSyncOperationRetentionDays: { en: "30", pl: "30" },
    consumerRequestRetentionYears: { en: "6", pl: "6" },
    controllerAddress: { en: "[TO BE COMPLETED: controllerAddress]", pl: "[DO UZUPEŁNIENIA: controllerAddress]" },
    controllerBusinessForm: { en: "[TO BE COMPLETED: controllerBusinessForm]", pl: "[DO UZUPEŁNIENIA: controllerBusinessForm]" },
    controllerLegalName: { en: "[TO BE COMPLETED: controllerLegalName]", pl: "[DO UZUPEŁNIENIA: controllerLegalName]" },
    controllerPhone: { en: "[TO BE COMPLETED: controllerPhone]", pl: "[DO UZUPEŁNIENIA: controllerPhone]" },
    deletionEvidenceRetentionYears: { en: "3", pl: "3" },
    deletionTombstoneRetentionDays: { en: "45", pl: "45" },
    distributionTerritories: { en: "[TO BE COMPLETED: distributionTerritories]", pl: "[DO UZUPEŁNIENIA: distributionTerritories]" },
    dpoContact: { en: "[TO BE COMPLETED: dpoContact]", pl: "[DO UZUPEŁNIENIA: dpoContact]" },
    effectiveDate: { en: "[TO BE COMPLETED: effectiveDate]", pl: "[DO UZUPEŁNIENIA: effectiveDate]" },
    emailDeliveryProvider: { en: "Google Workspace SMTP Relay", pl: "Google Workspace SMTP Relay" },
    hostingRegions: { en: "Google Cloud europe-central2 (Warsaw, Poland)", pl: "Google Cloud europe-central2 (Warszawa, Polska)" },
    internationalTransferSafeguards: { en: "[TO BE COMPLETED: internationalTransferSafeguards]", pl: "[DO UZUPEŁNIENIA: internationalTransferSafeguards]" },
    linkedReportRetentionDays: { en: "180", pl: "180" },
    localReportOutboxRetentionDays: { en: String(localReportOutboxRetentionDays), pl: String(localReportOutboxRetentionDays) },
    operationalLogRetentionDays: { en: "30", pl: "30" },
    privacyEmail: { en: "[TO BE COMPLETED: privacyEmail]", pl: "[DO UZUPEŁNIENIA: privacyEmail]" },
    reportRateLimitIdentifierRetentionSeconds: { en: "[TO BE COMPLETED: reportRateLimitIdentifierRetentionSeconds]", pl: "[DO UZUPEŁNIENIA: reportRateLimitIdentifierRetentionSeconds]" },
    processingRegisterDisclosure: { en: "[TO BE COMPLETED: processingRegisterDisclosure]", pl: "[DO UZUPEŁNIENIA: processingRegisterDisclosure]" },
    registrationNumber: { en: "[TO BE COMPLETED: registrationNumber]", pl: "[DO UZUPEŁNIENIA: registrationNumber]" },
    retentionRegisterDisclosure: { en: "Operational logs: 30 days. Security-relevant logs: 180 days. Completed synchronization operations and mutations: 30 days. Anonymous content reports: 30 days. Reports linked to an account or contact address at submission: 180 days. Consumer complaints, withdrawal statements, non-personal data-return requests and suspension appeals: 6 years from closure, unless a legal hold applies. Account-deletion tombstones: 45 days. Minimal deletion evidence and completed deletion-operation records: 3 years. Firestore PITR versions: up to 7 days; no additional scheduled Firestore backup is maintained. Deletion is performed by managed TTL and may occur after the stated expiry time because TTL processing is asynchronous.", pl: "Logi operacyjne: 30 dni. Logi dotyczące bezpieczeństwa: 180 dni. Ukończone operacje i mutacje synchronizacji: 30 dni. Anonimowe zgłoszenia treści: 30 dni. Zgłoszenia powiązane przy wysłaniu z kontem lub adresem kontaktowym: 180 dni. Reklamacje konsumenckie, oświadczenia o odstąpieniu, wnioski o zwrot danych nieosobowych i odwołania od zawieszenia: 6 lat od zamknięcia sprawy, chyba że obowiązuje legal hold. Pseudonimizowane blokady po usunięciu konta: 45 dni. Minimalne dowody usunięcia i ukończone rekordy operacji usunięcia: 3 lata. Wersje Firestore PITR: maksymalnie 7 dni; Patternly nie utrzymuje dodatkowej harmonogramowej kopii Firestore. Usuwanie realizuje zarządzany TTL i ze względu na asynchroniczne przetwarzanie może nastąpić po wskazanym terminie wygaśnięcia." },
    revenueCatStatus: { en: "[TO BE COMPLETED: revenueCatStatus]", pl: "[DO UZUPEŁNIENIA: revenueCatStatus]" },
    securityLogRetentionDays: { en: "180", pl: "180" },
    supervisoryAuthority: { en: "[TO BE COMPLETED: supervisoryAuthority]", pl: "[DO UZUPEŁNIENIA: supervisoryAuthority]" },
    taxIdentifier: { en: "[TO BE COMPLETED: taxIdentifier]", pl: "[DO UZUPEŁNIENIA: taxIdentifier]" },
  },
} as const;
