import type { IconName } from "./Icon";
import {
  AWS_CERTIFIED_SOLUTIONS_ARCHITECT_ASSOCIATE_TRACK_ID,
  BACKEND_SYSTEM_DESIGN_INTERVIEW_TRACK_ID,
  CLAUDE_CERTIFIED_ARCHITECT_PROFESSIONAL_CERTIFICATION_TRACK_ID,
  CODING_INTERVIEW_TRACK_ID,
  FRONTEND_SYSTEM_DESIGN_INTERVIEW_TRACK_ID,
  GOOGLE_CLOUD_ASSOCIATE_CLOUD_ENGINEER_TRACK_ID,
  MICROSOFT_AZURE_ADMINISTRATOR_ASSOCIATE_AZ_104_TRACK_ID,
  MICROSOFT_AZURE_AI_FUNDAMENTALS_AI_901_TRACK_ID,
  OBJECT_ORIENTED_DESIGN_INTERVIEW_TRACK_ID,
  type TrackId,
} from "../domain";

const TRACK_ICONS: Readonly<Record<string, IconName>> = {
  [AWS_CERTIFIED_SOLUTIONS_ARCHITECT_ASSOCIATE_TRACK_ID]: "cloud",
  [BACKEND_SYSTEM_DESIGN_INTERVIEW_TRACK_ID]: "database",
  [CLAUDE_CERTIFIED_ARCHITECT_PROFESSIONAL_CERTIFICATION_TRACK_ID]: "sparkle",
  [CODING_INTERVIEW_TRACK_ID]: "route",
  [FRONTEND_SYSTEM_DESIGN_INTERVIEW_TRACK_ID]: "device-phone",
  [GOOGLE_CLOUD_ASSOCIATE_CLOUD_ENGINEER_TRACK_ID]: "server-stack",
  [MICROSOFT_AZURE_ADMINISTRATOR_ASSOCIATE_AZ_104_TRACK_ID]: "settings",
  [MICROSOFT_AZURE_AI_FUNDAMENTALS_AI_901_TRACK_ID]: "cpu",
  [OBJECT_ORIENTED_DESIGN_INTERVIEW_TRACK_ID]: "grid",
};

export function getTrackIconName(trackId: TrackId): IconName {
  const iconName = TRACK_ICONS[trackId];
  if (!iconName) throw new Error(`No canonical icon is registered for track ${trackId}.`);
  return iconName;
}
