/** The only namespace for canonical user-owned records. */
const PREFIX = "patternly:canonical:v1:";
export const STORAGE_KEYS = {
  METADATA: `${PREFIX}metadata`,
  GUEST_INSTALLATION: `${PREFIX}guest-installation`,
  GUEST_ACCESS: `${PREFIX}guest-access`,
  ACTIVE_TRACK: `${PREFIX}active-track`,
  ACTIVE_TRAINING_SESSION: `${PREFIX}active-training-session`,
  ACTIVE_TRAINING_SESSION_DRAFT: `${PREFIX}active-training-session-draft`,
  ACTIVE_FOREGROUND_TIMER: `${PREFIX}active-foreground-timer`,
  trainingSession: (id: string) => `${PREFIX}training-session:${id}`,
  trainingSessionResult: (sessionId: string) => `${PREFIX}training-session-result:${sessionId}`,
  TRAINING_SESSION_INDEX: `${PREFIX}training-session-index`,
  trainingAttempt: (id: string) => `${PREFIX}training-attempt:${id}`,
  TRAINING_ATTEMPT_INDEX: `${PREFIX}training-attempt-index`,
  reviewEntry: (id: string) => `${PREFIX}review-entry:${id}`,
  REVIEW_INDEX: `${PREFIX}review-index`,
  SETTINGS: `${PREFIX}settings`,
  goal: (trackId: string) => `${PREFIX}goal:${trackId}`,
  learningPlan: (trackId: string) => `${PREFIX}learning-plan:${trackId}`,
  GOAL_ONBOARDING_PREFERENCES: `${PREFIX}goal-onboarding-preferences`,
  NOTIFICATION_SETTINGS: `${PREFIX}notification-settings`,
  NOTIFICATION_SETTINGS_JOURNAL: `${PREFIX}notification-settings-journal`,
  ACTIVE_JOURNAL: `${PREFIX}journal:active`,
  ACCOUNT_SYNC: `${PREFIX}account-sync`,
  ACCOUNT_SIGN_OUT: `${PREFIX}account-sign-out`,
  ACCOUNT_DELETION: `${PREFIX}account-deletion`,
  CONTENT_REPORT_OUTBOX: `${PREFIX}content-report-outbox`,
  /** Private stores for identity tombstones; never runtime learning keys. */
  ARCHIVAL_HISTORY_INDEX: `${PREFIX}archival-history-index`,
  archivalHistory: (sessionId: string) => `${PREFIX}archival-history:${sessionId}`,
  UNAVAILABLE_ACTIVE_INDEX: `${PREFIX}unavailable-active-index`,
  unavailableActive: (sessionId: string) => `${PREFIX}unavailable-active:${sessionId}`,
  UNAVAILABLE_REVIEW_INDEX: `${PREFIX}unavailable-review-index`,
  unavailableReview: (reviewId: string) => `${PREFIX}unavailable-review:${reviewId}`,
} as const;
export const STORAGE_NAMESPACE = PREFIX;
