import type { NativeStackScreenProps } from "@react-navigation/native-stack";
import { useFocusEffect } from "@react-navigation/native";
import type { ReactNode } from "react";
import { useCallback, useMemo, useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { Badge, Button, Card, EmptyState, ProgressBar, Screen, SectionHeader } from "../../components";
import { ROUTES } from "../../constants";
import type { RootStackParamList } from "../../navigation";
import { getAttempts, getReviewQueueItems } from "../../storage";
import { setQuestionNeedsReview } from "../practice/practiceService";
import type { CertificationAnswerViewModel, CertificationExamSummaryViewModel, CertificationQuestion } from "../../tracks/cloud-certification";
import { colors, radius, spacing, typography } from "../../theme";

type Props = NativeStackScreenProps<RootStackParamList, typeof ROUTES.ANSWER_REVIEW>;
type ReviewFilter = "all" | "incorrect";
export function AnswerReviewScreen({ route }: Props) {
  const [attempt, setAttempt] = useState<CertificationExamSummaryViewModel | null>(null);
  const [reviewIds, setReviewIds] = useState<Set<string>>(new Set());
  const [filter, setFilter] = useState<ReviewFilter>(route.params?.initialFilter ?? "all");
  useFocusEffect(useCallback(() => { let active = true; void Promise.all([getAttempts(), getReviewQueueItems()]).then(([attempts, reviews]) => { if (!active) return; setAttempt(attempts.find((item) => item.id === route.params?.attemptId) ?? attempts[0] ?? null); setReviewIds(new Set(reviews.value.map((entry) => entry.sourceItem.itemId))); }); return () => { active = false; }; }, [route.params?.attemptId]));
  const answers = useMemo(() => !attempt ? [] : filter === "incorrect" ? attempt.answers.filter((answer) => !answer.isCorrect) : attempt.answers, [attempt, filter]);
  async function toggle(answer: CertificationAnswerViewModel) { const next = new Set(reviewIds); const marked = !next.has(answer.questionId); marked ? next.add(answer.questionId) : next.delete(answer.questionId); setReviewIds(next); await setQuestionNeedsReview(answer.questionSnapshot, marked); }
  return <Screen>{attempt ? <><Card><SectionHeader title="Answer Review" subtitle={`${attempt.correctCount}/${attempt.questionCount} correct · ${attempt.scorePercent}%`} /><ProgressBar progress={attempt.scorePercent / 100} /><View style={styles.filterRow}><FilterChip active={filter === "all"} label="All" onPress={() => setFilter("all")} tone="info" /><FilterChip active={filter === "incorrect"} label="Incorrect" onPress={() => setFilter("incorrect")} tone="danger" /></View></Card>{answers.length ? <View style={styles.answerList}>{answers.map((answer) => <AnswerCard answer={answer} key={answer.questionId} needsReview={reviewIds.has(answer.questionId)} onToggle={() => void toggle(answer)} />)}</View> : <Card><EmptyState title="No answers in this view" description="Switch filters to review the full attempt." /></Card>}</> : <Card><EmptyState title="No attempt found" description="Submit an exam before reviewing answers." /></Card>}</Screen>;
}
function AnswerCard({ answer, needsReview, onToggle }: { answer: CertificationAnswerViewModel; needsReview: boolean; onToggle: () => void }) { const question = answer.questionSnapshot; return <Card variant={!answer.isAnswered || !answer.isCorrect ? "warning" : "default"}><SectionHeader title={`Question ${answer.questionNumber}`} subtitle={answer.isAnswered ? answer.isCorrect ? "Correct" : "Incorrect" : "Unanswered"} action={<Badge label={needsReview ? "Needs Review" : answer.wasFlagged ? "Flagged" : answer.isCorrect ? "Correct" : "Review"} tone={needsReview ? "warning" : answer.isCorrect ? "success" : "danger"} />} /><Text style={styles.questionText}>{question.question}</Text><DiagnosticBlock label="Selected answer" tone={answer.isCorrect ? "neutral" : "danger"} value={getOptionText(answer, answer.selectedOptionIds) || "No answer selected."} /><DiagnosticBlock label="Correct answer" tone="success" value={getOptionText(answer, answer.correctOptionIds)} /><DiagnosticBlock label="Explanation" value={question.explanation} /><Button variant={needsReview ? "primary" : "secondary"} onPress={onToggle}>{needsReview ? "Marked Needs Review" : "Mark Needs Review"}</Button></Card>; }
function getOptionText(answer: CertificationAnswerViewModel, ids: readonly string[]) { const byId = new Map(answer.questionSnapshot.options.map((option) => [option.id, option.text])); return ids.map((id) => byId.get(id) ?? id).join(", "); }
function DiagnosticBlock({ label, tone = "neutral", value, children }: { label: string; tone?: "neutral" | "success" | "danger"; value?: string; children?: ReactNode }) { return <View style={[styles.detailBlock, tone === "success" ? styles.successBlock : null, tone === "danger" ? styles.dangerBlock : null]}><Text style={styles.detailLabel}>{label}</Text>{value ? <Text style={styles.detailText}>{value}</Text> : children}</View>; }
function FilterChip({ active, label, onPress, tone }: { active: boolean; label: string; onPress: () => void; tone: "danger" | "info" }) { return <Pressable accessibilityRole="button" accessibilityState={{ selected: active }} onPress={onPress} style={({ pressed }) => [styles.filterChip, active ? styles[`${tone}FilterChip`] : null, pressed ? styles.pressed : null]}><Text style={[styles.filterChipText, active ? styles.activeFilterChipText : null]}>{label}</Text></Pressable>; }
const styles = StyleSheet.create({ answerList: { gap: spacing.lg }, filterRow: { flexDirection: "row", gap: spacing.sm }, filterChip: { borderColor: colors.dark.border, borderRadius: radius.pill, borderWidth: 1, paddingHorizontal: spacing.md, paddingVertical: spacing.sm }, infoFilterChip: { backgroundColor: colors.dark.infoSoft, borderColor: colors.dark.info }, dangerFilterChip: { backgroundColor: colors.dark.dangerSoft, borderColor: colors.dark.danger }, filterChipText: { ...typography.caption, color: colors.dark.textSecondary }, activeFilterChipText: { color: colors.dark.textPrimary }, pressed: { opacity: 0.8 }, questionText: { ...typography.bodyStrong, color: colors.dark.textPrimary }, detailBlock: { gap: spacing.xs, padding: spacing.md }, successBlock: { backgroundColor: colors.dark.successSoft }, dangerBlock: { backgroundColor: colors.dark.dangerSoft }, detailLabel: { ...typography.caption, color: colors.dark.textSecondary }, detailText: { ...typography.body, color: colors.dark.textPrimary } });
